// lib/tags/companions.ts
//
// Матриця супутників: які теги зазвичай потрібні разом із даним.
// Згенерована в кілька проходів із зовнішнім рев'ю (TookenClub) і
// перевірена на синтетичних запитах; вага 0.3–0.9 — наскільки ймовірно.
// Правити можна руками: tests/unit/tags.test.ts стежить за посиланнями.

export const COMPANIONS: Record<string, Record<string, number>> = {
  "1c-bas": { "inventory": 0.8, "orders": 0.8, "sync": 0.8, "accounting": 0.7, "invoicing": 0.7, "data-import": 0.6, "finance": 0.6, "pos-system": 0.5, "reports": 0.5, "warehouse-management": 0.5, "manufacturing-execution": 0.4, "migration": 0.4 },
  "accessibility": { "ui-ux-design": 0.6, "testing": 0.5, "content-editor": 0.3, "multilingual": 0.3, "redesign": 0.3 },
  "accounting": { "invoicing": 0.9, "reports": 0.8, "1c-bas": 0.7, "data-import": 0.7, "expense-management": 0.7, "medoc": 0.5 },
  "adalo": { "mobile-app": 0.6, "app-store-publishing": 0.5, "auth": 0.45, "firebase": 0.4, "online-payments": 0.4, "ui-ux-design": 0.4 },
  "admin-panel": { "roles": 0.8, "auth": 0.7, "reports": 0.6, "monitoring": 0.5, "workflow-builder": 0.5, "backups": 0.4 },
  "ads": { "analytics-setup": 0.7, "web-analytics": 0.7, "copywriting": 0.6, "landing": 0.6, "google-analytics": 0.5, "smm": 0.4 },
  "aggregator": { "data-import": 0.8, "search": 0.8, "sync": 0.7, "api-backend": 0.6, "monitoring": 0.5, "reports": 0.5, "web-analytics": 0.5 },
  "agro": { "inventory": 0.7, "orders": 0.6, "1c-bas": 0.5, "demand-forecasting": 0.5, "geolocation": 0.5, "reports": 0.5, "data-analytics": 0.4, "maps-stores": 0.4, "warehouse-management": 0.4 },
  "ai-agent": { "openai": 0.7, "api-backend": 0.6, "automation": 0.6, "workflow-builder": 0.6, "ai-integration": 0.5, "monitoring": 0.5, "rag": 0.5, "rpa": 0.5, "testing": 0.5, "security-audit": 0.4 },
  "ai-assistant": { "chat": 0.8, "openai": 0.7, "ai-integration": 0.6, "rag": 0.6, "ai-sales-assistant": 0.5, "ai-tutor": 0.5, "anthropic": 0.4, "monitoring": 0.4, "security-audit": 0.4 },
  "ai-code-fix": { "code-review": 0.7, "testing": 0.7, "ai-code-scaling": 0.6, "bug-fixing": 0.6, "refactoring": 0.6, "security-audit": 0.5 },
  "ai-code-scaling": { "ai-code-fix": 0.9, "architecture": 0.8, "performance": 0.8, "testing": 0.8, "code-review": 0.7, "devops": 0.6 },
  "ai-content": { "ai-text": 0.8, "content-editor": 0.7, "seo": 0.6, "ai-images": 0.5, "summarization": 0.5, "anthropic": 0.4, "multilingual": 0.4, "openai": 0.4 },
  "ai-customer-support": { "chat": 0.9, "ai-assistant": 0.8, "openai": 0.7, "rag": 0.6, "support-chat-services": 0.6, "ai-text": 0.5, "telegram-bot": 0.5 },
  "ai-deployment": { "devops": 0.9, "ai-integration": 0.8, "monitoring": 0.7, "aws": 0.5, "cloudflare": 0.5, "docker": 0.5 },
  "ai-images": { "ai-content": 0.6, "content-editor": 0.5, "openai": 0.5, "product-photo": 0.4, "ai-assistant": 0.3, "branding": 0.3 },
  "ai-integration": { "openai": 0.7, "ai-text": 0.6, "ai-deployment": 0.5, "anthropic": 0.5, "monitoring": 0.5, "rag": 0.5, "security-audit": 0.5, "testing": 0.5, "vector-database": 0.4 },
  "ai-meeting-notes": { "speech-to-text": 0.9, "summarization": 0.9, "zoom": 0.8, "calendar": 0.7, "ai-assistant": 0.6, "google-drive": 0.5 },
  "ai-model-training": { "ml-model": 0.9, "python": 0.8, "data-analytics": 0.7, "ai-integration": 0.6, "data-engineering": 0.6 },
  "ai-recruiter": { "hr-system": 0.9, "ats": 0.8, "job-board": 0.7, "forms": 0.6, "ai-assistant": 0.5, "openai": 0.5 },
  "ai-sales-assistant": { "crm": 0.9, "ai-assistant": 0.8, "chat": 0.8, "sales-pipeline": 0.7, "openai": 0.6, "online-store": 0.5 },
  "ai-text": { "ai-content": 0.7, "content-editor": 0.6, "openai": 0.6, "summarization": 0.6, "ai-assistant": 0.4, "translation": 0.4, "ai-images": 0.3 },
  "ai-tutor": { "education": 0.9, "ai-assistant": 0.8, "chat": 0.8, "speech-to-text": 0.7, "online-tests": 0.5, "mobile-app": 0.4 },
  "aiogram": { "telegram-api": 0.75, "telegram-bot": 0.75, "python": 0.65, "notifications": 0.4, "postgresql": 0.4, "redis": 0.35 },
  "airtable": { "automation": 0.7, "data-import": 0.6, "reports": 0.6, "sync": 0.6, "forms": 0.5, "n8n": 0.4, "workflow-builder": 0.4 },
  "analytics-setup": { "google-analytics": 0.8, "web-analytics": 0.8, "reports": 0.6, "product-analytics": 0.5, "ads": 0.4, "data-warehouse": 0.4, "etl": 0.4, "google-sheets": 0.4 },
  "android-app": { "app-store-publishing": 0.8, "auth": 0.7, "notifications": 0.7, "api-backend": 0.6, "testing": 0.5, "ui-ux-design": 0.5, "analytics-setup": 0.4 },
  "angular": { "typescript": 0.75, "testing": 0.55, "github": 0.45, "api-backend": 0.4, "github-actions": 0.4 },
  "animations": { "ui-ux-design": 0.7, "accessibility": 0.6, "performance": 0.5, "landing": 0.4 },
  "anthropic": { "ai-text": 0.8, "ai-assistant": 0.7, "rag": 0.7, "api-backend": 0.6, "ai-agent": 0.5, "ai-customer-support": 0.5, "ai-tutor": 0.4, "security-audit": 0.4, "summarization": 0.4, "webhooks": 0.4 },
  "anti-spam": { "forms": 0.7, "chat": 0.5, "auth": 0.4, "monitoring": 0.4 },
  "api-backend": { "auth": 0.7, "webhooks": 0.7, "monitoring": 0.6, "backups": 0.5, "documentation": 0.5, "security-audit": 0.5, "testing": 0.5, "architecture": 0.4 },
  "app": { "auth": 0.6, "notifications": 0.6, "ui-ux-design": 0.6, "api-backend": 0.5, "user-account": 0.5, "admin-panel": 0.4 },
  "app-store-publishing": { "mobile-app": 0.8, "android-app": 0.7, "ios-app": 0.7, "testing": 0.6 },
  "apple-google-pay": { "online-payments": 0.9, "cart-checkout": 0.7, "monobank": 0.5, "refunds": 0.5, "stripe": 0.5, "webhooks": 0.4 },
  "ar-app": { "mobile-app": 0.9, "threejs": 0.7, "unity": 0.7, "android-app": 0.5, "ios-app": 0.5, "ui-ux-design": 0.4 },
  "architecture": { "devops": 0.6, "security-audit": 0.6, "spec-writing": 0.6, "monitoring": 0.5, "testing": 0.5, "code-review": 0.4, "performance": 0.4, "data-warehouse": 0.3 },
  "art": { "portfolio-site": 0.8, "events": 0.5, "online-store": 0.5, "product-photo": 0.5, "event-website": 0.4, "online-payments": 0.4, "seo": 0.4 },
  "astro": { "seo": 0.7, "tailwind": 0.6, "typescript": 0.6, "content-editor": 0.5, "vercel": 0.5, "accessibility": 0.4, "multilingual": 0.4 },
  "ats": { "hr-system": 0.8, "calendar": 0.7, "notifications": 0.6, "user-account": 0.6, "reports": 0.5, "email-marketing": 0.4 },
  "auction-platform": { "marketplace": 0.9, "online-payments": 0.8, "notifications": 0.7, "user-profiles": 0.7, "search": 0.6, "realtime": 0.5 },
  "audiobook-app": { "mobile-app": 0.7, "offline-mode": 0.7, "search": 0.7, "subscriptions": 0.6, "sync": 0.5, "notifications": 0.4 },
  "auth": { "user-account": 0.8, "roles": 0.6, "sso": 0.5, "two-factor": 0.5, "security-audit": 0.3 },
  "auto": { "online-booking": 0.7, "catalog": 0.6, "inventory": 0.6, "car-maintenance-app": 0.5, "crm": 0.5, "forms": 0.5, "online-payments": 0.5, "field-service": 0.4, "google-maps": 0.4, "reviews": 0.4 },
  "automation": { "workflow-builder": 0.8, "rpa": 0.7, "sync": 0.7, "webhooks": 0.7, "google-sheets": 0.6, "n8n": 0.6, "data-import": 0.4, "monitoring": 0.4, "testing": 0.4 },
  "aws": { "devops": 0.8, "docker": 0.7, "github-actions": 0.6, "monitoring": 0.6, "postgresql": 0.6, "backups": 0.55, "security-audit": 0.55, "architecture": 0.5 },
  "b2b-portal": { "catalog": 0.8, "orders": 0.8, "user-account": 0.8, "wholesale-pricing": 0.8, "invoicing": 0.7, "roles": 0.6 },
  "baby-tracker": { "parenting-app": 0.9, "calendar": 0.7, "mobile-app": 0.7, "notifications": 0.7, "family-organizer": 0.5, "reports": 0.5 },
  "backups": { "devops": 0.5, "monitoring": 0.5, "security-audit": 0.5, "support": 0.3 },
  "bankid": { "auth": 0.9, "two-factor": 0.6, "diia": 0.5, "finance": 0.5, "security-audit": 0.4, "webhooks": 0.4 },
  "barcode-scanner": { "mobile-app": 0.8, "inventory": 0.7, "data-import": 0.5, "online-store": 0.5, "offline-mode": 0.4, "search": 0.4 },
  "base44": { "web-app": 0.55, "ui-ux-design": 0.45, "github": 0.4, "supabase": 0.4, "testing": 0.4 },
  "beauty": { "online-booking": 0.8, "calendar": 0.7, "notifications": 0.6, "forms": 0.5, "instagram": 0.5, "loyalty": 0.5, "online-payments": 0.5, "sms": 0.4 },
  "binotel": { "call-tracking": 0.9, "crm": 0.8, "notifications": 0.6, "bitrix24": 0.5, "reports": 0.5, "webhooks": 0.5, "salesdrive": 0.4, "sync": 0.4 },
  "bitrix24": { "crm": 0.8, "tasks": 0.8, "marketing-automation": 0.6, "notifications": 0.6, "sales-pipeline": 0.6, "calendar": 0.5, "crm-setup": 0.5, "forms": 0.5, "reports": 0.5, "roles": 0.5, "workflow-builder": 0.4 },
  "blender": { "motion-design": 0.6, "threejs": 0.5, "unity": 0.5, "product-photo": 0.4 },
  "blog": { "content-editor": 0.9, "seo": 0.7, "web-analytics": 0.6, "email-marketing": 0.5, "multilingual": 0.4 },
  "bolt-new": { "github": 0.55, "web-app": 0.55, "supabase": 0.5, "ui-ux-design": 0.45, "testing": 0.4, "vercel": 0.4 },
  "booking-platform": { "calendar": 0.8, "online-booking": 0.8, "notifications": 0.7, "online-payments": 0.7, "user-account": 0.6, "google-calendar": 0.5, "rental-management": 0.5, "waitlist": 0.5 },
  "bot-scenarios": { "chat-bot": 0.7, "telegram-bot": 0.6, "manychat": 0.5, "sendpulse-bots": 0.5, "telegram-api": 0.5, "ai-customer-support": 0.4, "copywriting": 0.4, "viber-api": 0.4, "whatsapp-api": 0.4 },
  "graphic-design": { "branding": 0.6, "smm": 0.55, "ads": 0.55, "copywriting": 0.45, "product-photo": 0.4 },
  "branding": { "ui-ux-design": 0.7, "copywriting": 0.6, "landing": 0.5, "website": 0.5, "product-photo": 0.4, "smm": 0.4 },
  "browser-automation": { "testing": 0.7, "github-actions": 0.5, "web-app": 0.5, "bug-fixing": 0.4, "monitoring": 0.4, "performance": 0.4 },
  "browser-extension": { "auth": 0.5, "legal-docs": 0.5, "security-audit": 0.5, "testing": 0.5, "app-store-publishing": 0.4, "ui-ux-design": 0.4 },
  "bubble": { "web-app": 0.75, "stripe": 0.45, "ui-ux-design": 0.45, "api-backend": 0.4, "automation": 0.4, "supabase": 0.4, "testing": 0.4 },
  "budgeting-forecasting": { "accounting": 0.8, "data-analytics": 0.8, "reports": 0.8, "dashboard": 0.7, "data-import": 0.6, "expense-management": 0.6 },
  "bug-fixing": { "testing": 0.7, "code-review": 0.5, "monitoring": 0.5, "performance": 0.4, "refactoring": 0.4, "support": 0.4, "ai-code-scaling": 0.3 },
  "building-materials": { "catalog": 0.8, "inventory": 0.7, "online-store": 0.7, "orders": 0.7, "delivery": 0.6, "warehouse-management": 0.6, "1c-bas": 0.5, "wholesale-pricing": 0.5, "nova-poshta": 0.4, "online-payments": 0.4, "prom": 0.4 },
  "business-card-site": { "ui-ux-design": 0.6, "content-editor": 0.5, "seo": 0.5, "forms": 0.4, "web-analytics": 0.4 },
  "calculator": { "forms": 0.7, "shipping-calculator": 0.5, "ui-ux-design": 0.5, "web-analytics": 0.5, "api-backend": 0.4, "reports": 0.4 },
  "calendar": { "online-booking": 0.7, "google-calendar": 0.6, "notifications": 0.6, "planner-app": 0.6, "reminder-app": 0.5, "user-account": 0.4, "realtime": 0.3 },
  "calendly": { "online-booking": 0.9, "calendar": 0.8, "google-calendar": 0.7, "notifications": 0.6, "online-payments": 0.4 },
  "call-tracking": { "binotel": 0.6, "web-analytics": 0.6, "crm": 0.5, "google-analytics": 0.5, "reports": 0.4 },
  "calorie-tracker": { "barcode-scanner": 0.8, "fitness-app": 0.8, "mobile-app": 0.8, "reports": 0.6, "notifications": 0.5, "data-import": 0.4 },
  "car-maintenance-app": { "auto": 0.8, "reminder-app": 0.8, "calendar": 0.7, "notifications": 0.7, "mobile-app": 0.6, "expense-management": 0.5 },
  "car-marketplace": { "auto": 0.9, "classifieds": 0.9, "search": 0.8, "user-profiles": 0.7, "forms": 0.5, "online-payments": 0.4 },
  "cart-checkout": { "catalog": 0.8, "online-payments": 0.8, "delivery": 0.7, "orders": 0.7, "checkbox": 0.6, "nova-poshta": 0.6, "product-bundles": 0.6, "prom": 0.5, "wayforpay": 0.5, "digital-goods-store": 0.4, "liqpay": 0.4, "rozetka": 0.4, "ukrposhta": 0.4, "installments": 0.3 },
  "catalog": { "cart-checkout": 0.7, "search": 0.7, "inventory": 0.6, "online-store": 0.6, "product-bundles": 0.5, "reviews": 0.5, "wholesale-pricing": 0.5, "data-import": 0.4, "online-payments": 0.4, "wishlist": 0.4 },
  "certificates": { "lms": 0.5, "online-tests": 0.5, "user-account": 0.5, "notifications": 0.4, "content-editor": 0.3 },
  "charity": { "donation-platform": 0.8, "online-payments": 0.8, "reports": 0.6, "forms": 0.5, "monobank": 0.5, "notifications": 0.5 },
  "chat": { "notifications": 0.6, "support-chat-services": 0.6, "user-account": 0.5, "webhooks": 0.4, "monitoring": 0.3 },
  "chat-bot": { "bot-scenarios": 0.7, "ai-customer-support": 0.6, "notifications": 0.6, "ai-sales-assistant": 0.5, "ai-text": 0.5, "chat": 0.5, "forms": 0.5 },
  "chatgpt": { "ai-text": 0.8, "openai": 0.8, "ai-integration": 0.7, "chat-bot": 0.5, "prompt-engineering": 0.5, "rag": 0.5 },
  "checkbox": { "pos-system": 0.8, "cart-checkout": 0.7, "online-payments": 0.7, "online-store": 0.6, "orders": 0.6, "api-backend": 0.5, "retail": 0.5 },
  "class-schedule": { "calendar": 0.7, "online-booking": 0.7, "notifications": 0.5, "fitness": 0.4, "online-payments": 0.4, "user-account": 0.4, "education": 0.3 },
  "classifieds": { "search": 0.9, "chat": 0.7, "moderation": 0.7, "user-profiles": 0.7, "real-estate-listing-platform": 0.6, "car-marketplace": 0.5, "notifications": 0.5, "online-payments": 0.4 },
  "claude-ai": { "anthropic": 0.8, "ai-text": 0.7, "ai-integration": 0.6, "prompt-engineering": 0.5, "rag": 0.5, "chat-bot": 0.4 },
  "claude-code": { "github": 0.65, "testing": 0.55, "code-review": 0.45, "github-actions": 0.45, "typescript": 0.4 },
  "clickup": { "tasks": 0.9, "calendar": 0.6, "time-tracking": 0.6, "google-calendar": 0.5, "notifications": 0.5, "google-drive": 0.4, "reports": 0.4 },
  "clinic-management": { "patient-records": 0.9, "online-booking": 0.8, "medicine": 0.7, "notifications": 0.6, "ehealth": 0.5, "invoicing": 0.4 },
  "cloudflare": { "monitoring": 0.45, "security-audit": 0.45, "github": 0.35, "web-app": 0.35 },
  "code-review": { "testing": 0.7, "refactoring": 0.6, "security-audit": 0.6, "architecture": 0.5, "bug-fixing": 0.5, "ai-code-scaling": 0.4 },
  "codex": { "github": 0.65, "testing": 0.55, "code-review": 0.45, "github-actions": 0.45, "monitoring": 0.35 },
  "comments": { "notifications": 0.5, "user-account": 0.5, "moderation": 0.4, "realtime": 0.4, "reports": 0.3 },
  "community": { "auth": 0.8, "user-profiles": 0.8, "chat": 0.7, "moderation": 0.7, "comments": 0.6, "notifications": 0.6, "reports": 0.4 },
  "construction": { "forms": 0.7, "crm": 0.6, "invoicing": 0.6, "portfolio-site": 0.6, "field-service": 0.5, "procurement": 0.5, "task-manager": 0.5, "google-sheets": 0.4, "legal-docs": 0.4, "quotations": 0.4, "seo": 0.4 },
  "consulting": { "spec-writing": 0.7, "architecture": 0.6, "analytics-setup": 0.4, "testing": 0.4, "ui-ux-design": 0.4, "ux-research": 0.4 },
  "content-editor": { "ai-text": 0.5, "multilingual": 0.5, "seo": 0.5, "blog": 0.4, "roles": 0.4, "wordpress": 0.4, "backups": 0.3, "strapi": 0.3 },
  "content-filling": { "content-editor": 0.6, "copywriting": 0.6, "product-photo": 0.5, "seo": 0.5, "localization": 0.4, "multilingual": 0.4 },
  "contract-management": { "document-management": 0.8, "e-signature": 0.8, "notifications": 0.6, "search": 0.6, "roles": 0.5, "invoicing": 0.4 },
  "copywriting": { "content-filling": 0.6, "seo": 0.6, "landing": 0.5, "branding": 0.4, "localization": 0.4 },
  "corporate-site": { "content-editor": 0.8, "multilingual": 0.6, "seo": 0.6, "web-analytics": 0.6, "forms": 0.5, "ui-ux-design": 0.5, "accessibility": 0.4, "security-audit": 0.3 },
  "cosmetics": { "catalog": 0.8, "online-store": 0.8, "cart-checkout": 0.7, "nova-poshta": 0.7, "online-payments": 0.7, "loyalty": 0.5, "product-photo": 0.4, "reviews": 0.4, "subscription-store": 0.4, "ukrposhta": 0.4, "wayforpay": 0.4 },
  "coworking": { "calendar": 0.7, "online-booking": 0.7, "online-payments": 0.6, "notifications": 0.5, "property-management": 0.5, "user-account": 0.5, "forms": 0.4, "maps-stores": 0.4, "accessibility": 0.3 },
  "crm": { "sales-pipeline": 0.8, "auth": 0.7, "roles": 0.7, "tasks": 0.7, "quotations": 0.6, "reports": 0.6, "ai-sales-assistant": 0.5, "automation": 0.5, "crm-setup": 0.5, "data-import": 0.5, "forms": 0.5, "notifications": 0.5, "webhooks": 0.5 },
  "crm-setup": { "crm": 0.8, "data-import": 0.6, "marketing-automation": 0.6, "sync": 0.6, "analytics-setup": 0.5, "keycrm": 0.5, "salesdrive": 0.5, "bitrix24": 0.4 },
  "crypto": { "crypto-wallet": 0.7, "online-payments": 0.7, "security-audit": 0.7, "auth": 0.6, "two-factor": 0.6, "monitoring": 0.5, "web3": 0.4, "webhooks": 0.4 },
  "crypto-payments": { "online-payments": 0.8, "web3": 0.7, "api-backend": 0.6, "crypto-wallet": 0.5, "security-audit": 0.5, "webhooks": 0.5 },
  "crypto-wallet": { "web3": 0.9, "crypto-payments": 0.8, "security-audit": 0.8, "mobile-app": 0.7, "auth": 0.6, "two-factor": 0.6 },
  "cursor": { "github": 0.65, "testing": 0.55, "github-actions": 0.45, "code-review": 0.4, "typescript": 0.4 },
  "dark-mode": { "accessibility": 0.7, "ui-ux-design": 0.6, "web-app": 0.4, "mobile-app": 0.3 },
  "dashboard": { "data-analytics": 0.8, "reports": 0.7, "data-import": 0.6, "google-sheets": 0.5, "sync": 0.5, "web-analytics": 0.4 },
  "data-analytics": { "reports": 0.8, "data-import": 0.7, "data-warehouse": 0.7, "analytics-setup": 0.6, "demand-forecasting": 0.6, "etl": 0.6, "google-sheets": 0.6, "pandas": 0.5, "sync": 0.5, "monitoring": 0.4 },
  "data-engineering": { "etl": 0.9, "data-warehouse": 0.8, "data-analytics": 0.7, "python": 0.7, "postgresql": 0.5, "monitoring": 0.4 },
  "data-import": { "sync": 0.6, "data-analytics": 0.5, "excel": 0.5, "reports": 0.5, "google-sheets": 0.4 },
  "data-warehouse": { "data-analytics": 0.9, "etl": 0.9, "reports": 0.7, "demand-forecasting": 0.5, "monitoring": 0.4, "postgresql": 0.4 },
  "dating-app": { "chat": 0.9, "user-profiles": 0.9, "mobile-app": 0.8, "moderation": 0.8, "geolocation": 0.7, "notifications": 0.7 },
  "dealer-management": { "b2b-portal": 0.9, "catalog": 0.8, "orders": 0.8, "inventory": 0.7, "wholesale-pricing": 0.7, "reports": 0.5 },
  "delivery": { "orders": 0.8, "nova-poshta": 0.7, "geolocation": 0.6, "notifications": 0.6, "route-planning": 0.6, "shipment-management": 0.6, "cart-checkout": 0.5, "ukrposhta": 0.4, "meest": 0.3, "sms": 0.3 },
  "delivery-app": { "delivery": 0.8, "geolocation": 0.8, "orders": 0.8, "notifications": 0.7, "route-planning": 0.7, "online-payments": 0.6, "realtime": 0.6, "google-maps": 0.5, "shipment-management": 0.5, "nova-poshta": 0.4 },
  "demand-forecasting": { "data-analytics": 0.9, "inventory": 0.8, "ml-model": 0.8, "reports": 0.7, "data-warehouse": 0.6, "etl": 0.5 },
  "dentistry": { "online-booking": 0.8, "patient-records": 0.8, "clinic-management": 0.7, "notifications": 0.6, "forms": 0.5, "online-payments": 0.5, "helsi": 0.4, "roles": 0.4, "web-app": 0.4 },
  "desktop-app": { "offline-mode": 0.6, "auth": 0.5, "testing": 0.5, "ui-ux-design": 0.5, "monitoring": 0.4, "security-audit": 0.4 },
  "devops": { "docker": 0.7, "github-actions": 0.7, "monitoring": 0.7, "aws": 0.6, "backups": 0.6, "architecture": 0.5, "security-audit": 0.5, "ai-deployment": 0.4 },
  "digital-goods-store": { "online-store": 0.9, "catalog": 0.8, "online-payments": 0.8, "user-account": 0.6, "file-upload": 0.5, "subscriptions": 0.5 },
  "diia": { "e-signature": 0.8, "auth": 0.7, "bankid": 0.6, "government": 0.5, "legal-docs": 0.4, "webhooks": 0.4 },
  "directory": { "search": 0.8, "maps-stores": 0.7, "content-editor": 0.6, "geolocation": 0.5, "reviews": 0.5, "seo": 0.5, "web-analytics": 0.5 },
  "discord-bot": { "bot-scenarios": 0.7, "auth": 0.5, "moderation": 0.5, "notifications": 0.5, "monitoring": 0.4 },
  "django": { "python": 0.7, "postgresql": 0.65, "api-backend": 0.55, "auth": 0.45, "testing": 0.45, "docker": 0.4, "redis": 0.35 },
  "docker": { "devops": 0.8, "github-actions": 0.7, "aws": 0.6, "kubernetes": 0.6, "monitoring": 0.6, "postgresql": 0.6, "security-audit": 0.5 },
  "document-management": { "file-upload": 0.8, "search": 0.7, "e-signature": 0.6, "roles": 0.6, "notifications": 0.5, "backups": 0.4 },
  "documentation": { "wiki": 0.7, "spec-writing": 0.6, "architecture": 0.5, "support": 0.5, "code-review": 0.4, "testing": 0.4, "ai-meeting-notes": 0.3 },
  "donation-platform": { "charity": 0.8, "online-payments": 0.8, "reports": 0.6, "liqpay": 0.5, "monobank": 0.5, "notifications": 0.5, "diia": 0.4, "wayforpay": 0.4, "gift-cards": 0.3 },
  "dotnet": { "api-backend": 0.6, "testing": 0.5, "github": 0.45, "docker": 0.4, "postgresql": 0.4, "redis": 0.35 },
  "driving-school": { "class-schedule": 0.7, "online-booking": 0.7, "calendar": 0.6, "online-payments": 0.6, "notifications": 0.5, "school-management": 0.5, "forms": 0.4, "online-tests": 0.4 },
  "e-signature": { "invoicing": 0.7, "vchasno": 0.6, "auth": 0.5, "diia": 0.5, "user-account": 0.5, "legal-docs": 0.4 },
  "easypay": { "online-payments": 0.9, "invoicing": 0.6, "refunds": 0.5, "api-backend": 0.4, "notifications": 0.4, "webhooks": 0.4 },
  "ebook-reader": { "offline-mode": 0.8, "mobile-app": 0.7, "search": 0.7, "subscriptions": 0.6, "sync": 0.5, "user-account": 0.4 },
  "ecommerce": { "cart-checkout": 0.8, "catalog": 0.8, "nova-poshta": 0.8, "online-payments": 0.8, "online-store": 0.8, "orders": 0.7, "checkbox": 0.6, "inventory": 0.6, "liqpay": 0.6, "wayforpay": 0.6, "monobank": 0.5, "reviews": 0.5, "ukrposhta": 0.5, "digital-goods-store": 0.4, "meest": 0.4, "prom": 0.4, "rozetka": 0.4, "subscription-store": 0.4 },
  "education": { "lms": 0.8, "online-tests": 0.7, "class-schedule": 0.6, "user-account": 0.6, "ai-tutor": 0.5, "certificates": 0.5, "notifications": 0.5, "online-payments": 0.5, "school-management": 0.5, "forms": 0.4 },
  "ehealth": { "medicine": 0.9, "patient-records": 0.9, "auth": 0.6, "clinic-management": 0.6, "security-audit": 0.6, "reports": 0.5, "roles": 0.5 },
  "elderly-care": { "accessibility": 0.7, "notifications": 0.6, "forms": 0.5, "online-booking": 0.5, "family-organizer": 0.4, "online-payments": 0.4, "roles": 0.4, "user-account": 0.4 },
  "electronics": { "catalog": 0.8, "online-store": 0.8, "cart-checkout": 0.7, "nova-poshta": 0.7, "online-payments": 0.7, "inventory": 0.6, "checkbox": 0.5, "warehouse-management": 0.5, "product-bundles": 0.4, "reviews": 0.4, "ukrposhta": 0.4, "wayforpay": 0.4 },
  "elevenlabs": { "voice-bot": 0.8, "ai-assistant": 0.6, "api-backend": 0.5, "audiobook-app": 0.4, "video-editing": 0.4, "webhooks": 0.4 },
  "email-app": { "email-marketing": 0.7, "marketing-automation": 0.6, "analytics-setup": 0.5, "automation": 0.5, "notifications": 0.5, "resend": 0.5, "ai-customer-support": 0.4 },
  "email-marketing": { "marketing-automation": 0.7, "sendpulse": 0.5, "user-account": 0.5, "web-analytics": 0.5, "crm": 0.4, "esputnik": 0.4, "forms": 0.4 },
  "employee-onboarding": { "hr-system": 0.9, "tasks": 0.8, "file-upload": 0.6, "notifications": 0.6, "roles": 0.6, "ats": 0.5, "e-signature": 0.5, "leave-management": 0.4 },
  "energy": { "monitoring": 0.8, "data-analytics": 0.7, "reports": 0.6, "iot": 0.5, "maintenance-management": 0.5, "notifications": 0.5, "security-audit": 0.4 },
  "epicentr": { "online-store": 0.9, "catalog": 0.8, "orders": 0.8, "delivery": 0.6, "inventory": 0.6, "keycrm": 0.6, "nova-poshta": 0.6, "online-payments": 0.6, "reports": 0.5, "product-bundles": 0.3, "wholesale-pricing": 0.3 },
  "erp": { "inventory": 0.8, "accounting": 0.7, "reports": 0.7, "roles": 0.7, "1c-bas": 0.6, "data-import": 0.6, "procurement": 0.6, "sync": 0.6, "warehouse-management": 0.6, "api-backend": 0.5, "medoc": 0.5, "vchasno": 0.4 },
  "esputnik": { "email-marketing": 0.9, "marketing-automation": 0.8, "sms": 0.7, "online-store": 0.6, "sync": 0.5, "web-analytics": 0.5, "reports": 0.4 },
  "etl": { "data-import": 0.8, "sync": 0.8, "data-analytics": 0.7, "data-warehouse": 0.7, "api-backend": 0.5, "monitoring": 0.4 },
  "etsy-amazon": { "catalog": 0.8, "online-store": 0.8, "inventory": 0.7, "orders": 0.7, "online-payments": 0.6, "paypal": 0.6, "sync": 0.6, "delivery": 0.5, "digital-goods-store": 0.4, "product-bundles": 0.3 },
  "event-registration": { "events": 0.9, "forms": 0.8, "ticketing-platform": 0.8, "email-marketing": 0.7, "online-payments": 0.6, "qr": 0.6 },
  "event-website": { "events": 0.9, "ticketing-platform": 0.8, "event-registration": 0.7, "forms": 0.7, "online-payments": 0.6, "calendar": 0.5, "multilingual": 0.4 },
  "events": { "event-registration": 0.7, "online-booking": 0.7, "online-payments": 0.7, "ticketing-platform": 0.7, "event-website": 0.6, "qr": 0.6, "calendar": 0.5, "forms": 0.5, "notifications": 0.5, "email-marketing": 0.4, "facebook": 0.4 },
  "excel": { "data-import": 0.8, "reports": 0.7, "sync": 0.6, "1c-bas": 0.5, "finance": 0.5, "inventory": 0.4, "accounting": 0.3, "demand-forecasting": 0.3 },
  "expense-management": { "accounting": 0.9, "reports": 0.7, "data-import": 0.6, "file-upload": 0.6, "1c-bas": 0.5, "budgeting-forecasting": 0.5, "invoicing": 0.5 },
  "expo": { "react-native": 0.75, "mobile-app": 0.65, "app-store-publishing": 0.55, "testing": 0.45, "android-app": 0.4, "firebase": 0.4, "ios-app": 0.4 },
  "face-recognition": { "auth": 0.7, "security-audit": 0.7, "mobile-app": 0.6, "two-factor": 0.5 },
  "facebook": { "ads": 0.8, "smm": 0.8, "instagram": 0.7, "marketing-automation": 0.6, "social-sharing": 0.5, "web-analytics": 0.5 },
  "family-organizer": { "calendar": 0.9, "shopping-list": 0.8, "tasks": 0.8, "mobile-app": 0.7, "notifications": 0.7, "user-account": 0.5 },
  "fashion": { "catalog": 0.8, "online-store": 0.8, "cart-checkout": 0.7, "nova-poshta": 0.7, "online-payments": 0.7, "wishlist": 0.5, "loyalty": 0.4, "product-bundles": 0.4, "product-photo": 0.4, "reviews": 0.4, "ukrposhta": 0.4, "wayforpay": 0.4 },
  "fastapi": { "python": 0.75, "api-backend": 0.65, "postgresql": 0.55, "testing": 0.45, "docker": 0.4, "redis": 0.35 },
  "field-service": { "calendar": 0.8, "geolocation": 0.8, "tasks": 0.8, "route-planning": 0.7, "file-upload": 0.6, "notifications": 0.6 },
  "figma": { "ui-ux-design": 0.8, "branding": 0.5, "redesign": 0.5 },
  "file-upload": { "forms": 0.6, "user-account": 0.5, "backups": 0.4, "security-audit": 0.4 },
  "finance": { "invoicing": 0.8, "accounting": 0.7, "reports": 0.7, "auth": 0.6, "expense-management": 0.6, "online-payments": 0.6, "budgeting-forecasting": 0.5, "security-audit": 0.5, "two-factor": 0.5, "bankid": 0.4, "monobank": 0.4, "diia": 0.3 },
  "finance-tracker": { "reports": 0.8, "expense-management": 0.7, "budgeting-forecasting": 0.6, "data-import": 0.6, "notifications": 0.5, "finance": 0.4, "online-payments": 0.4, "security-audit": 0.4, "web-analytics": 0.4 },
  "finmap": { "accounting": 0.8, "expense-management": 0.7, "reports": 0.55, "budgeting-forecasting": 0.5, "finance": 0.5, "invoicing": 0.5, "finance-tracker": 0.45, "google-sheets": 0.45, "data-analytics": 0.4 },
  "firebase": { "auth": 0.65, "notifications": 0.55, "mobile-app": 0.5, "google-analytics": 0.4, "monitoring": 0.4, "backups": 0.35 },
  "firebase-studio": { "firebase": 0.7, "web-app": 0.5, "github": 0.45, "monitoring": 0.4, "testing": 0.4 },
  "fitness": { "class-schedule": 0.8, "memberships": 0.8, "fitness-app": 0.7, "online-booking": 0.7, "online-payments": 0.6, "notifications": 0.5, "user-account": 0.5, "qr": 0.4 },
  "fitness-app": { "class-schedule": 0.7, "memberships": 0.7, "user-profiles": 0.6, "calendar": 0.5, "habit-tracker": 0.5, "notifications": 0.5, "tasks": 0.5, "online-payments": 0.4 },
  "flashcards-app": { "education": 0.8, "gamification": 0.7, "mobile-app": 0.7, "online-tests": 0.7, "offline-mode": 0.6, "sync": 0.5 },
  "fleet-management": { "geolocation": 0.9, "maintenance-management": 0.8, "reports": 0.7, "route-planning": 0.7, "data-analytics": 0.6, "expense-management": 0.5, "notifications": 0.5 },
  "flowers-gifts": { "online-store": 0.8, "cart-checkout": 0.7, "catalog": 0.7, "delivery": 0.7, "nova-poshta": 0.6, "online-payments": 0.6, "gift-cards": 0.5, "notifications": 0.5, "product-bundles": 0.5, "loyalty": 0.4, "product-photo": 0.4, "wayforpay": 0.4 },
  "flutter": { "mobile-app": 0.75, "app-store-publishing": 0.6, "firebase": 0.55, "testing": 0.5, "android-app": 0.4, "auth": 0.4, "ios-app": 0.4 },
  "flutterflow": { "flutter": 0.65, "mobile-app": 0.6, "firebase": 0.55, "app-store-publishing": 0.5, "testing": 0.45, "supabase": 0.4 },
  "fondy": { "online-payments": 0.9, "cart-checkout": 0.8, "orders": 0.7, "refunds": 0.6, "webhooks": 0.6, "api-backend": 0.5, "apple-google-pay": 0.5, "subscriptions": 0.4, "digital-goods-store": 0.3, "subscription-store": 0.3 },
  "food-ordering": { "online-menu": 0.9, "restaurants": 0.9, "delivery": 0.8, "orders": 0.8, "online-payments": 0.7, "kitchen-display": 0.6, "glovo": 0.4 },
  "food-production": { "inventory": 0.8, "orders": 0.7, "1c-bas": 0.6, "manufacturing-execution": 0.6, "quality-management": 0.6, "invoicing": 0.5, "reports": 0.5, "checkbox": 0.4, "data-import": 0.4, "medoc": 0.4, "wholesale": 0.4 },
  "forms": { "notifications": 0.6, "email-marketing": 0.5, "google-sheets": 0.5, "anti-spam": 0.4, "crm": 0.4, "web-analytics": 0.4 },
  "forms-services": { "forms": 0.9, "google-sheets": 0.65, "event-registration": 0.6, "notifications": 0.5, "email-marketing": 0.45, "waitlist": 0.4, "web-analytics": 0.4 },
  "framer": { "landing": 0.55, "ui-ux-design": 0.55, "seo": 0.45, "website": 0.45, "forms": 0.4, "web-analytics": 0.4 },
  "franchise-management": { "reports": 0.8, "roles": 0.8, "inventory": 0.7, "content-editor": 0.6, "user-account": 0.6, "orders": 0.5 },
  "furniture": { "catalog": 0.8, "online-store": 0.7, "cart-checkout": 0.6, "delivery": 0.6, "inventory": 0.6, "product-photo": 0.5, "nova-poshta": 0.4, "online-payments": 0.4, "product-bundles": 0.4, "rental-management": 0.4, "reviews": 0.4 },
  "game": { "auth": 0.5, "testing": 0.5, "unity": 0.5, "user-profiles": 0.5, "notifications": 0.4 },
  "gamification": { "loyalty": 0.5, "user-account": 0.5, "notifications": 0.4, "web-analytics": 0.4 },
  "gaming": { "game": 0.8, "user-profiles": 0.6, "auth": 0.5, "online-payments": 0.5, "chat": 0.4, "gamification": 0.4, "moderation": 0.4, "streaming-platform": 0.4, "unity": 0.4, "web-app": 0.4 },
  "gcp-azure": { "devops": 0.8, "docker": 0.6, "github-actions": 0.6, "monitoring": 0.6, "security-audit": 0.5 },
  "gemini": { "ai-text": 0.8, "ai-assistant": 0.7, "api-backend": 0.6, "ai-agent": 0.5, "ai-images": 0.5, "rag": 0.5, "ai-tutor": 0.4, "summarization": 0.4, "webhooks": 0.4 },
  "gemini-cli": { "gemini": 0.7, "ai-integration": 0.6, "testing": 0.5, "github-actions": 0.4, "python": 0.4, "typescript": 0.4 },
  "geolocation": { "google-maps": 0.7, "maps-stores": 0.6, "navigation-app": 0.6, "route-planning": 0.6, "delivery": 0.5, "map-service": 0.5, "search": 0.3 },
  "gift-cards": { "online-payments": 0.8, "online-store": 0.8, "email-marketing": 0.6, "loyalty": 0.6, "online-booking": 0.4, "subscriptions": 0.4 },
  "github": { "github-actions": 0.65, "testing": 0.6, "code-review": 0.5, "monitoring": 0.45, "docker": 0.4, "sentry": 0.35 },
  "github-actions": { "github": 0.8, "testing": 0.7, "devops": 0.6, "docker": 0.6, "monitoring": 0.5, "security-audit": 0.4, "sentry": 0.4 },
  "github-copilot": { "github": 0.65, "testing": 0.55, "github-actions": 0.45, "code-review": 0.4, "typescript": 0.4 },
  "glide": { "google-sheets": 0.55, "web-app": 0.5, "internal-tool": 0.45, "auth": 0.4, "reports": 0.4, "roles": 0.4, "automation": 0.35 },
  "glovo": { "delivery": 0.9, "orders": 0.8, "restaurants": 0.8, "online-menu": 0.7, "food-ordering": 0.6, "poster": 0.6, "grocery-delivery": 0.5, "online-payments": 0.5, "table-booking": 0.4 },
  "godot": { "game": 0.9, "blender": 0.6, "testing": 0.6, "app-store-publishing": 0.5, "mobile-app": 0.5, "android-app": 0.4, "ios-app": 0.4 },
  "golang": { "api-backend": 0.6, "postgresql": 0.5, "docker": 0.45, "github": 0.45, "testing": 0.45, "redis": 0.35 },
  "google-analytics": { "web-analytics": 0.9, "reports": 0.7, "seo": 0.6, "ads": 0.5, "google-merchant": 0.5, "google-sheets": 0.5 },
  "google-calendar": { "calendar": 0.9, "online-booking": 0.8, "notifications": 0.6, "video-calls": 0.4, "workforce-scheduling": 0.4 },
  "google-drive": { "content-editor": 0.6, "data-import": 0.6, "google-sheets": 0.6, "sync": 0.6, "file-upload": 0.5, "backups": 0.4, "document-management": 0.4, "microsoft-365": 0.4 },
  "google-maps": { "maps-stores": 0.9, "geolocation": 0.8, "delivery": 0.6, "map-service": 0.6, "google-analytics": 0.4, "online-booking": 0.4 },
  "google-merchant": { "catalog": 0.8, "online-store": 0.8, "ads": 0.6, "google-analytics": 0.6, "sync": 0.6, "reports": 0.5, "web-analytics": 0.5 },
  "google-sheets": { "data-import": 0.7, "reports": 0.7, "sync": 0.7, "automation": 0.6, "google-drive": 0.5, "google-analytics": 0.4, "accounting": 0.3, "demand-forecasting": 0.3 },
  "government": { "forms": 0.8, "auth": 0.7, "diia": 0.7, "e-signature": 0.7, "accessibility": 0.6, "bankid": 0.6, "document-management": 0.6, "security-audit": 0.5, "web-portal": 0.5, "notifications": 0.4, "roles": 0.4, "workflow-builder": 0.4 },
  "grocery-delivery": { "delivery": 0.9, "online-store": 0.9, "catalog": 0.8, "inventory": 0.8, "cart-checkout": 0.7, "orders": 0.7, "nova-poshta": 0.4 },
  "gsap": { "animations": 0.8, "performance": 0.6, "threejs": 0.5, "ui-ux-design": 0.5, "testing": 0.4 },
  "habit-tracker": { "notifications": 0.6, "reminder-app": 0.6, "gamification": 0.5, "planner-app": 0.5, "reports": 0.5, "offline-mode": 0.4 },
  "handmade": { "online-store": 0.7, "cart-checkout": 0.6, "catalog": 0.6, "online-payments": 0.6, "nova-poshta": 0.5, "product-photo": 0.5, "etsy-amazon": 0.4, "reviews": 0.4, "ukrposhta": 0.4, "digital-goods-store": 0.3 },
  "helpdesk": { "ai-customer-support": 0.7, "chat": 0.7, "notifications": 0.7, "roles": 0.6, "automation": 0.5, "reports": 0.5, "support-chat-services": 0.5, "moderation": 0.4 },
  "helsi": { "medicine": 0.8, "patient-records": 0.8, "online-booking": 0.7, "clinic-management": 0.6, "ehealth": 0.6, "auth": 0.5, "notifications": 0.5, "reports": 0.4 },
  "home-inventory": { "search": 0.8, "file-upload": 0.6, "mobile-app": 0.6, "barcode-scanner": 0.5, "reports": 0.5, "web-app": 0.5 },
  "home-services": { "online-booking": 0.8, "field-service": 0.7, "forms": 0.7, "calendar": 0.6, "notifications": 0.5, "online-payments": 0.5, "route-planning": 0.5, "google-maps": 0.4, "maps-stores": 0.4, "reviews": 0.4 },
  "horoshop": { "online-store": 0.9, "cart-checkout": 0.8, "catalog": 0.8, "delivery": 0.8, "nova-poshta": 0.8, "online-payments": 0.8, "checkbox": 0.6, "keycrm": 0.6, "refunds": 0.5, "reports": 0.5, "product-bundles": 0.4, "subscription-store": 0.3 },
  "hospitality-tech": { "online-booking": 0.7, "table-booking": 0.7, "online-payments": 0.6, "restaurant-management": 0.6, "calendar": 0.5, "online-menu": 0.5, "poster": 0.5, "table-ordering": 0.5, "checkbox": 0.4, "notifications": 0.4, "orders": 0.4 },
  "hotels": { "online-booking": 0.8, "online-payments": 0.7, "property-management": 0.7, "booking-platform": 0.6, "calendar": 0.6, "notifications": 0.5, "rental-management": 0.5, "forms": 0.4, "google-maps": 0.4, "maps-stores": 0.4, "multilingual": 0.4 },
  "hotline": { "price-monitoring": 0.8, "catalog": 0.7, "online-store": 0.7, "sync": 0.6, "google-merchant": 0.5, "reports": 0.4, "demand-forecasting": 0.3 },
  "hr": { "hr-system": 0.8, "ats": 0.7, "auth": 0.6, "employee-onboarding": 0.6, "roles": 0.6, "job-board": 0.5, "leave-management": 0.5, "notifications": 0.5, "reports": 0.5, "forms": 0.4, "google-calendar": 0.4, "user-account": 0.4 },
  "hr-system": { "ats": 0.7, "auth": 0.7, "roles": 0.7, "employee-onboarding": 0.6, "time-tracking": 0.6, "leave-management": 0.5, "notifications": 0.5, "reports": 0.5, "user-profiles": 0.5, "microsoft-365": 0.4 },
  "hubspot": { "crm": 0.9, "email-marketing": 0.8, "marketing-automation": 0.8, "sales-pipeline": 0.7, "forms": 0.6, "web-analytics": 0.6, "crm-setup": 0.5, "reports": 0.5, "ai-sales-assistant": 0.4, "calendar": 0.4 },
  "instagram": { "smm": 0.8, "ads": 0.7, "instagram-bot": 0.7, "content-editor": 0.5, "marketing-automation": 0.5, "social-sharing": 0.5 },
  "instagram-bot": { "instagram": 0.9, "bot-scenarios": 0.8, "manychat": 0.6, "crm-setup": 0.5, "notifications": 0.4 },
  "installments": { "online-payments": 0.7, "orders": 0.6, "cart-checkout": 0.5, "monobank": 0.5, "refunds": 0.4 },
  "insurance": { "forms": 0.8, "invoicing": 0.6, "online-payments": 0.6, "auth": 0.5, "contract-management": 0.5, "e-signature": 0.5, "notifications": 0.5, "bankid": 0.4, "diia": 0.4, "document-management": 0.4, "reports": 0.4, "security-audit": 0.4 },
  "integration-service": { "sync": 0.8, "webhooks": 0.8, "api-backend": 0.6, "monitoring": 0.6, "workflow-builder": 0.6, "data-import": 0.5, "etl": 0.5, "testing": 0.5 },
  "internal-tool": { "auth": 0.7, "roles": 0.7, "automation": 0.6, "data-import": 0.5, "google-sheets": 0.5, "sync": 0.5, "user-account": 0.5, "testing": 0.4 },
  "inventory": { "orders": 0.7, "warehouse-management": 0.7, "data-import": 0.6, "sync": 0.6, "1c-bas": 0.5, "demand-forecasting": 0.5, "reports": 0.5, "online-store": 0.4, "keycrm": 0.3 },
  "investment-tracker": { "finance": 0.8, "reports": 0.8, "data-import": 0.7, "data-analytics": 0.6, "mobile-app": 0.5, "notifications": 0.5 },
  "invoicing": { "accounting": 0.7, "online-payments": 0.7, "orders": 0.6, "e-signature": 0.5, "vchasno": 0.5, "1c-bas": 0.4, "medoc": 0.4, "diia": 0.3 },
  "ios-app": { "app-store-publishing": 0.8, "auth": 0.7, "notifications": 0.7, "api-backend": 0.6, "testing": 0.5, "ui-ux-design": 0.5, "analytics-setup": 0.4 },
  "iot": { "iot-dashboard": 0.8, "api-backend": 0.7, "monitoring": 0.7, "realtime": 0.7, "security-audit": 0.5 },
  "iot-dashboard": { "dashboard": 0.9, "api-backend": 0.8, "realtime": 0.8, "monitoring": 0.7, "geolocation": 0.5, "iot": 0.5 },
  "it-company": { "task-manager": 0.7, "crm": 0.6, "github": 0.6, "wiki": 0.6, "api-backend": 0.5, "monitoring": 0.5, "sso": 0.5, "ai-code-scaling": 0.4, "backups": 0.4, "security-audit": 0.4, "web-app": 0.4 },
  "java": { "api-backend": 0.6, "postgresql": 0.5, "testing": 0.5, "docker": 0.45, "github": 0.45, "redis": 0.35 },
  "javascript": { "typescript": 0.55, "testing": 0.5, "github": 0.45, "github-actions": 0.4, "nodejs": 0.4, "web-app": 0.4 },
  "jewelry": { "online-store": 0.8, "cart-checkout": 0.7, "catalog": 0.7, "nova-poshta": 0.6, "online-payments": 0.6, "product-photo": 0.5, "loyalty": 0.4, "reviews": 0.4, "wayforpay": 0.4, "digital-goods-store": 0.3 },
  "jira": { "tasks": 0.9, "github": 0.7, "comments": 0.6, "reports": 0.5, "documentation": 0.4, "monitoring": 0.4, "ai-code-scaling": 0.3 },
  "job-board": { "search": 0.8, "ats": 0.7, "forms": 0.7, "user-profiles": 0.7, "notifications": 0.6, "ai-recruiter": 0.5, "seo": 0.5, "moderation": 0.4 },
  "kasta": { "catalog": 0.8, "online-store": 0.8, "orders": 0.8, "inventory": 0.7, "delivery": 0.6, "keycrm": 0.6, "online-payments": 0.6, "refunds": 0.4, "product-bundles": 0.3 },
  "keycrm": { "orders": 0.9, "sync": 0.8, "crm": 0.7, "inventory": 0.7, "online-store": 0.7, "nova-poshta": 0.6, "sales-pipeline": 0.6, "online-payments": 0.5, "reports": 0.5, "shipment-management": 0.4 },
  "kids": { "online-booking": 0.6, "parenting-app": 0.6, "forms": 0.5, "notifications": 0.5, "online-payments": 0.5, "user-account": 0.5, "accessibility": 0.4, "baby-tracker": 0.4 },
  "kitchen-display": { "pos-system": 0.9, "orders": 0.8, "restaurant-management": 0.8, "realtime": 0.7, "food-ordering": 0.5, "notifications": 0.5, "poster": 0.5 },
  "kommo": { "crm": 0.9, "chat": 0.8, "sales-pipeline": 0.7, "marketing-automation": 0.6, "telegram-api": 0.6, "whatsapp-api": 0.6, "crm-setup": 0.5, "forms": 0.5, "notifications": 0.5, "ai-sales-assistant": 0.4 },
  "kotlin": { "android-app": 0.75, "mobile-app": 0.65, "app-store-publishing": 0.6, "testing": 0.5, "firebase": 0.4, "auth": 0.35 },
  "kubernetes": { "docker": 0.9, "devops": 0.8, "monitoring": 0.8, "github-actions": 0.7, "aws": 0.6, "security-audit": 0.5 },
  "laboratory-information-system": { "medical-labs": 0.9, "patient-records": 0.8, "reports": 0.7, "file-upload": 0.6, "data-import": 0.5, "ehealth": 0.5 },
  "landing": { "forms": 0.7, "ui-ux-design": 0.7, "copywriting": 0.6, "web-analytics": 0.6, "ads": 0.5, "seo": 0.5, "accessibility": 0.4 },
  "langchain": { "ai-integration": 0.8, "openai": 0.7, "rag": 0.7, "python": 0.6, "semantic-search": 0.6, "vector-database": 0.6, "anthropic": 0.5, "monitoring": 0.5, "ai-customer-support": 0.4 },
  "langfuse": { "monitoring": 0.9, "ai-agent": 0.7, "langchain": 0.6, "openai": 0.6, "ai-deployment": 0.5, "testing": 0.4 },
  "language-learning-app": { "education": 0.8, "gamification": 0.8, "mobile-app": 0.7, "online-tests": 0.7, "notifications": 0.6, "flashcards-app": 0.5, "offline-mode": 0.5 },
  "languages": { "class-schedule": 0.7, "lms": 0.7, "language-learning-app": 0.6, "online-tests": 0.6, "flashcards-app": 0.5, "online-booking": 0.5, "online-payments": 0.5, "certificates": 0.4, "notifications": 0.4, "video-calls": 0.4 },
  "laravel": { "php": 0.75, "api-backend": 0.6, "mysql": 0.55, "testing": 0.45, "docker": 0.4, "postgresql": 0.4, "redis": 0.35 },
  "leave-management": { "hr-system": 0.9, "calendar": 0.8, "workforce-scheduling": 0.7, "notifications": 0.6, "roles": 0.6, "reports": 0.5 },
  "legal": { "contract-management": 0.7, "e-signature": 0.7, "forms": 0.7, "document-management": 0.6, "invoicing": 0.6, "online-booking": 0.6, "file-upload": 0.5, "google-drive": 0.5, "legal-docs": 0.5, "auth": 0.4, "user-account": 0.4, "vchasno": 0.4 },
  "legal-docs": { "consulting": 0.4, "e-signature": 0.4, "security-audit": 0.3 },
  "linkedin": { "recruitment-agency": 0.75, "hr": 0.65, "job-board": 0.6, "ats": 0.5, "crm": 0.5, "marketing-agency": 0.45, "ai-recruiter": 0.4, "business-card-site": 0.35 },
  "liqpay": { "online-payments": 0.9, "cart-checkout": 0.8, "orders": 0.7, "refunds": 0.7, "webhooks": 0.6, "api-backend": 0.5, "checkbox": 0.5, "digital-goods-store": 0.3, "subscription-store": 0.3 },
  "lms": { "auth": 0.8, "online-tests": 0.8, "video-streaming": 0.7, "ai-tutor": 0.6, "certificates": 0.6, "flashcards-app": 0.6, "online-payments": 0.6, "roles": 0.6, "user-profiles": 0.6, "class-schedule": 0.5 },
  "localization": { "multilingual": 0.8, "translation": 0.6, "content-filling": 0.5, "copywriting": 0.5, "seo": 0.4, "testing": 0.4 },
  "logistics": { "delivery": 0.8, "orders": 0.8, "shipment-management": 0.8, "nova-poshta": 0.7, "route-planning": 0.7, "geolocation": 0.6, "inventory": 0.6, "warehouse-management": 0.6, "1c-bas": 0.5, "api-backend": 0.5, "reports": 0.5, "ukrposhta": 0.5, "meest": 0.4, "webhooks": 0.4 },
  "lovable": { "supabase": 0.65, "github": 0.55, "web-app": 0.55, "ui-ux-design": 0.45, "testing": 0.4, "vercel": 0.4 },
  "loyalty": { "online-store": 0.6, "user-account": 0.6, "marketing-automation": 0.5, "notifications": 0.5, "crm": 0.4, "referral": 0.4, "online-payments": 0.3 },
  "mailchimp": { "email-marketing": 0.9, "marketing-automation": 0.7, "online-store": 0.5, "web-analytics": 0.5, "forms": 0.4, "reports": 0.4, "sync": 0.4 },
  "maintenance-management": { "tasks": 0.8, "calendar": 0.7, "inventory": 0.6, "notifications": 0.6, "reports": 0.6, "field-service": 0.5, "fleet-management": 0.5 },
  "make-com": { "workflow-builder": 0.8, "automation": 0.75, "webhooks": 0.55, "google-sheets": 0.5, "rpa": 0.5, "notifications": 0.45, "crm": 0.4, "api-backend": 0.35 },
  "manufacturing": { "inventory": 0.8, "manufacturing-execution": 0.8, "1c-bas": 0.7, "orders": 0.7, "quality-management": 0.7, "reports": 0.6, "data-import": 0.5, "warehouse-management": 0.5, "invoicing": 0.4, "monitoring": 0.4 },
  "manufacturing-execution": { "inventory": 0.8, "orders": 0.8, "quality-management": 0.8, "manufacturing": 0.7, "reports": 0.7, "dashboard": 0.5, "demand-forecasting": 0.5 },
  "manychat": { "instagram": 0.7, "chat-bot": 0.65, "marketing-automation": 0.55, "ai-customer-support": 0.5, "instagram-bot": 0.5, "crm": 0.45, "notifications": 0.4, "online-payments": 0.35 },
  "map-service": { "geolocation": 0.8, "search": 0.8, "maps-stores": 0.7, "google-maps": 0.6, "navigation-app": 0.6, "realtime": 0.5, "transit-app": 0.5 },
  "mapbox": { "map-service": 0.9, "geolocation": 0.8, "maps-stores": 0.7, "delivery": 0.5, "search": 0.5, "webhooks": 0.4 },
  "maps-stores": { "google-maps": 0.7, "geolocation": 0.6, "navigation-app": 0.4, "search": 0.4, "content-editor": 0.3, "web-analytics": 0.3 },
  "marketing-agency": { "crm": 0.7, "marketing-automation": 0.7, "web-analytics": 0.7, "reports": 0.6, "forms": 0.5, "google-analytics": 0.5, "sales-pipeline": 0.5, "ads": 0.4, "facebook": 0.4, "product-analytics": 0.4, "quotations": 0.4, "seo": 0.4, "smm": 0.4 },
  "marketing-automation": { "email-marketing": 0.7, "crm": 0.5, "web-analytics": 0.5, "workflow-builder": 0.5, "notifications": 0.4, "google-analytics": 0.3 },
  "marketplace": { "multi-vendor": 0.9, "catalog": 0.8, "online-payments": 0.8, "cart-checkout": 0.7, "orders": 0.7, "reviews": 0.7, "search": 0.7, "user-profiles": 0.7, "moderation": 0.6, "rental-marketplace": 0.6, "auction-platform": 0.5, "chat": 0.5, "nova-poshta": 0.5, "refunds": 0.5 },
  "mcp": { "ai-integration": 0.7, "security-audit": 0.6, "anthropic": 0.5, "claude-ai": 0.5, "testing": 0.5, "chatgpt": 0.4, "workflow-builder": 0.4 },
  "meal-planner": { "recipes-app": 0.9, "shopping-list": 0.9, "calendar": 0.8, "mobile-app": 0.7, "notifications": 0.6 },
  "media": { "blog": 0.8, "content-editor": 0.8, "search": 0.6, "streaming-platform": 0.6, "web-analytics": 0.6, "email-marketing": 0.5, "video-streaming": 0.5, "seo": 0.4, "summarization": 0.4, "donation-platform": 0.3 },
  "medical-labs": { "laboratory-information-system": 0.8, "patient-records": 0.8, "online-booking": 0.7, "reports": 0.7, "ehealth": 0.6, "clinic-management": 0.5, "forms": 0.5, "notifications": 0.5, "security-audit": 0.5, "auth": 0.4 },
  "medicine": { "clinic-management": 0.8, "online-booking": 0.8, "patient-records": 0.8, "auth": 0.6, "forms": 0.6, "helsi": 0.5, "notifications": 0.5, "roles": 0.5, "security-audit": 0.5, "ehealth": 0.4, "diia": 0.3 },
  "meditation-app": { "mobile-app": 0.8, "notifications": 0.6, "offline-mode": 0.5, "sleep-tracker": 0.5, "subscriptions": 0.5 },
  "medoc": { "invoicing": 0.8, "1c-bas": 0.7, "finance": 0.7, "e-signature": 0.6, "accounting": 0.5, "reports": 0.5, "vchasno": 0.5, "data-import": 0.4, "document-management": 0.4 },
  "meest": { "delivery": 0.7, "orders": 0.7, "online-store": 0.6, "shipment-management": 0.6, "cart-checkout": 0.5, "online-payments": 0.5, "nova-poshta": 0.4, "ukrposhta": 0.4, "webhooks": 0.4 },
  "memberships": { "subscriptions": 0.6, "online-payments": 0.5, "user-account": 0.5, "loyalty": 0.4, "notifications": 0.4, "education": 0.3, "fitness": 0.3 },
  "mentoring": { "consulting": 0.6, "architecture": 0.4, "code-review": 0.4, "testing": 0.4, "spec-writing": 0.3 },
  "messaging-app": { "chat": 0.9, "realtime": 0.9, "mobile-app": 0.8, "notifications": 0.8, "file-upload": 0.7, "auth": 0.5 },
  "microsoft-365": { "calendar": 0.6, "sync": 0.6, "google-calendar": 0.5, "invoicing": 0.5, "document-management": 0.4, "google-drive": 0.4, "notifications": 0.4 },
  "migration": { "backups": 0.7, "data-import": 0.6, "testing": 0.6, "architecture": 0.5, "support": 0.5, "sync": 0.4 },
  "military": { "security-audit": 0.8, "donation-platform": 0.7, "auth": 0.6, "online-payments": 0.6, "roles": 0.6, "notifications": 0.5, "maintenance-management": 0.4 },
  "ml-model": { "data-analytics": 0.7, "data-import": 0.7, "api-backend": 0.6, "demand-forecasting": 0.6, "monitoring": 0.5, "pandas": 0.5, "testing": 0.5, "security-audit": 0.4 },
  "mobile-app": { "auth": 0.7, "notifications": 0.7, "api-backend": 0.6, "app-store-publishing": 0.6, "testing": 0.5, "ui-ux-design": 0.5, "analytics-setup": 0.4 },
  "moderation": { "community": 0.5, "reviews": 0.5, "anti-spam": 0.4, "comments": 0.4, "roles": 0.4 },
  "monday": { "task-manager": 0.65, "workflow-builder": 0.6, "automation": 0.55, "notifications": 0.45, "calendar": 0.4, "google-sheets": 0.4, "slack": 0.4, "reports": 0.35 },
  "mongodb": { "backups": 0.55, "api-backend": 0.45, "monitoring": 0.45, "docker": 0.35, "webhooks": 0.3 },
  "monitoring": { "sentry": 0.6, "backups": 0.5, "devops": 0.5, "security-audit": 0.4, "reports": 0.3 },
  "monobank": { "online-payments": 0.9, "apple-google-pay": 0.7, "invoicing": 0.6, "refunds": 0.6, "api-backend": 0.5, "checkbox": 0.5, "webhooks": 0.4, "accounting": 0.3, "expense-management": 0.3 },
  "motion-design": { "video-editing": 0.6, "branding": 0.4, "gsap": 0.4, "smm": 0.4, "threejs": 0.4, "video-streaming": 0.4 },
  "multi-vendor": { "marketplace": 0.8, "orders": 0.7, "online-payments": 0.6, "rental-marketplace": 0.5, "roles": 0.5, "cart-checkout": 0.4, "delivery": 0.4, "invoicing": 0.4 },
  "multilingual": { "translation": 0.7, "content-editor": 0.5, "localization": 0.5, "search": 0.4, "seo": 0.4 },
  "music-streaming-app": { "mobile-app": 0.8, "recommendations": 0.8, "search": 0.8, "subscriptions": 0.7, "offline-mode": 0.6, "user-account": 0.4 },
  "mvp": { "ui-ux-design": 0.7, "architecture": 0.6, "spec-writing": 0.6, "testing": 0.5, "ux-research": 0.5, "analytics-setup": 0.4 },
  "mysql": { "backups": 0.55, "monitoring": 0.45, "api-backend": 0.4, "data-import": 0.35, "docker": 0.35, "reports": 0.35 },
  "n8n": { "workflow-builder": 0.8, "automation": 0.75, "webhooks": 0.65, "rpa": 0.5, "google-sheets": 0.45, "notifications": 0.45, "api-backend": 0.4, "crm": 0.4, "monitoring": 0.4 },
  "navigation-app": { "geolocation": 0.9, "mobile-app": 0.9, "maps-stores": 0.8, "offline-mode": 0.8, "search": 0.7, "realtime": 0.5 },
  "netlify": { "github": 0.6, "github-actions": 0.5, "monitoring": 0.5, "performance": 0.5, "vercel": 0.4 },
  "nextjs": { "react": 0.7, "vercel": 0.65, "typescript": 0.6, "github": 0.45, "testing": 0.45, "postgresql": 0.4, "seo": 0.4, "ui-ux-design": 0.35 },
  "nodejs": { "api-backend": 0.65, "typescript": 0.55, "postgresql": 0.5, "github": 0.45, "docker": 0.4, "monitoring": 0.4, "redis": 0.4, "github-actions": 0.35 },
  "notes-app": { "search": 0.8, "sync": 0.8, "offline-mode": 0.7, "mobile-app": 0.6, "web-app": 0.6, "file-upload": 0.4 },
  "notifications": { "orders": 0.5, "sms": 0.5, "telegram-api": 0.4, "turbosms": 0.4, "user-account": 0.4, "email-marketing": 0 },
  "notion": { "wiki": 0.8, "tasks": 0.7, "comments": 0.5, "documentation": 0.5, "sync": 0.5, "ai-meeting-notes": 0.4, "content-editor": 0.4, "summarization": 0.3 },
  "nova-poshta": { "cart-checkout": 0.7, "online-store": 0.7, "orders": 0.7, "shipment-management": 0.7, "online-payments": 0.6, "delivery": 0.5, "inventory": 0.5, "meest": 0.4, "ukrposhta": 0.4, "webhooks": 0.4 },
  "nuxt": { "vue": 0.7, "typescript": 0.55, "github": 0.45, "vercel": 0.45, "seo": 0.4, "testing": 0.4 },
  "ocr": { "data-import": 0.6, "invoicing": 0.5, "reports": 0.4, "1c-bas": 0.3, "ai-text": 0.3, "openai": 0.3 },
  "offline-mode": { "sync": 0.7, "backups": 0.4, "mobile-app": 0.4, "monitoring": 0.4, "realtime": 0.3 },
  "ollama": { "ai-agent": 0.7, "python": 0.6, "rag": 0.6, "mcp": 0.5, "vector-database": 0.5, "ai-deployment": 0.4 },
  "olx": { "classifieds": 0.9, "forms": 0.7, "chat": 0.6, "notifications": 0.5, "car-marketplace": 0.4, "real-estate-listing-platform": 0.4, "rental-marketplace": 0.3 },
  "online-booking": { "calendar": 0.8, "notifications": 0.7, "online-payments": 0.6, "forms": 0.5, "google-calendar": 0.5, "rental-management": 0.5, "user-account": 0.5, "waitlist": 0.5, "sms": 0.4 },
  "online-menu": { "catalog": 0.8, "qr": 0.8, "restaurant-management": 0.6, "table-booking": 0.6, "table-ordering": 0.6, "online-payments": 0.5, "poster": 0.5, "restaurants": 0.4 },
  "online-payments": { "orders": 0.8, "refunds": 0.7, "cart-checkout": 0.6, "checkbox": 0.6, "invoicing": 0.6, "liqpay": 0.5, "monobank": 0.5, "wayforpay": 0.5, "apple-google-pay": 0.4, "fondy": 0.4 },
  "online-store": { "cart-checkout": 0.9, "catalog": 0.9, "delivery": 0.8, "nova-poshta": 0.8, "online-payments": 0.8, "orders": 0.8, "checkbox": 0.7, "inventory": 0.7, "digital-goods-store": 0.6, "liqpay": 0.6, "product-bundles": 0.6, "refunds": 0.6, "wayforpay": 0.6, "keycrm": 0.5, "loyalty": 0.5, "prom": 0.5, "rozetka": 0.5, "seo": 0.5, "subscription-store": 0.5, "ukrposhta": 0.5 },
  "online-tests": { "certificates": 0.6, "lms": 0.5, "reports": 0.5, "user-account": 0.5, "ai-tutor": 0.4, "education": 0.4, "flashcards-app": 0.4, "notifications": 0.4 },
  "openai": { "ai-text": 0.8, "ai-assistant": 0.7, "api-backend": 0.6, "rag": 0.6, "ai-customer-support": 0.5, "chat": 0.5, "ai-tutor": 0.4, "security-audit": 0.4, "summarization": 0.4, "webhooks": 0.4 },
  "opencart": { "online-store": 0.8, "cart-checkout": 0.75, "nova-poshta": 0.7, "catalog": 0.65, "online-payments": 0.65, "delivery": 0.6, "checkbox": 0.55, "liqpay": 0.55, "orders": 0.55, "ukrposhta": 0.55, "wayforpay": 0.55, "digital-goods-store": 0.5, "product-bundles": 0.5, "wholesale-pricing": 0.5, "monobank": 0.45, "inventory": 0.4, "prom": 0.4, "rozetka": 0.4, "seo": 0.4 },
  "opendatabot": { "data-import": 0.6, "reports": 0.6, "crm": 0.5, "finance": 0.4, "prozorro": 0.4 },
  "optics": { "catalog": 0.7, "online-booking": 0.7, "inventory": 0.6, "online-payments": 0.5, "forms": 0.4, "maps-stores": 0.4, "online-store": 0.4, "reviews": 0.4, "user-account": 0.4 },
  "orders": { "cart-checkout": 0.8, "delivery": 0.7, "online-payments": 0.7, "inventory": 0.6, "notifications": 0.6, "shipment-management": 0.6, "online-store": 0.5, "restaurant-management": 0.5, "keycrm": 0.4, "salesdrive": 0.4, "poster": 0.3 },
  "pandas": { "data-analytics": 0.8, "python": 0.8, "data-import": 0.6, "reports": 0.6, "excel": 0.5, "google-sheets": 0.4, "postgresql": 0.4 },
  "parenting-app": { "kids": 0.8, "calendar": 0.7, "notifications": 0.7, "family-organizer": 0.6, "mobile-app": 0.6, "user-account": 0.4 },
  "parser": { "data-import": 0.7, "etl": 0.6, "monitoring": 0.5, "reports": 0.5, "browser-automation": 0.4, "testing": 0.4 },
  "patient-records": { "auth": 0.6, "backups": 0.6, "medicine": 0.6, "roles": 0.6, "monitoring": 0.5, "dentistry": 0.4, "security-audit": 0.4 },
  "paypal": { "online-payments": 0.9, "cart-checkout": 0.7, "refunds": 0.6, "ecommerce": 0.5, "webhooks": 0.5, "api-backend": 0.4, "digital-goods-store": 0.4, "etsy-amazon": 0.4 },
  "payroll": { "hr-system": 0.9, "accounting": 0.8, "time-tracking": 0.8, "reports": 0.7, "leave-management": 0.6, "1c-bas": 0.5 },
  "performance": { "monitoring": 0.6, "testing": 0.6, "architecture": 0.5, "code-review": 0.4, "devops": 0.4, "seo": 0.4 },
  "period-tracker": { "calendar": 0.9, "mobile-app": 0.8, "notifications": 0.8, "user-account": 0.5, "reports": 0.4 },
  "personal-site": { "ui-ux-design": 0.6, "content-editor": 0.5, "seo": 0.5, "forms": 0.4, "web-analytics": 0.4 },
  "pet-care-app": { "calendar": 0.8, "reminder-app": 0.8, "veterinary": 0.8, "mobile-app": 0.7, "notifications": 0.7, "maps-stores": 0.4, "user-account": 0.4 },
  "pharmacy": { "catalog": 0.8, "inventory": 0.8, "online-store": 0.7, "delivery": 0.6, "online-payments": 0.6, "checkbox": 0.5, "orders": 0.5, "nova-poshta": 0.4, "warehouse-management": 0.4 },
  "photo-editor-app": { "mobile-app": 0.8, "file-upload": 0.7, "ai-images": 0.6, "offline-mode": 0.5, "subscriptions": 0.5 },
  "photo-video": { "portfolio-site": 0.8, "booking-platform": 0.6, "photo-editor-app": 0.6, "video-editor-app": 0.6, "file-upload": 0.5, "forms": 0.5, "product-photo": 0.5, "cloudflare": 0.4, "online-booking": 0.4, "seo": 0.4, "user-profiles": 0.4 },
  "php": { "mysql": 0.5, "api-backend": 0.45, "github": 0.4, "laravel": 0.4, "testing": 0.4, "docker": 0.35 },
  "pipedrive": { "crm": 0.9, "sales-pipeline": 0.8, "email-marketing": 0.6, "notifications": 0.6, "reports": 0.6, "calendar": 0.5, "forms": 0.5, "google-calendar": 0.5, "quotations": 0.4, "sync": 0.4 },
  "planner-app": { "calendar": 0.9, "tasks": 0.8, "mobile-app": 0.7, "notifications": 0.7, "web-app": 0.6, "user-account": 0.4 },
  "podcast-app": { "mobile-app": 0.7, "offline-mode": 0.7, "search": 0.7, "notifications": 0.5, "recommendations": 0.5, "subscriptions": 0.5 },
  "portfolio-site": { "ui-ux-design": 0.7, "content-editor": 0.6, "seo": 0.5, "web-analytics": 0.5, "accessibility": 0.4 },
  "portmone": { "online-payments": 0.9, "cart-checkout": 0.7, "invoicing": 0.6, "refunds": 0.5, "webhooks": 0.5, "api-backend": 0.4, "digital-goods-store": 0.3, "subscription-store": 0.3 },
  "pos-system": { "checkbox": 0.8, "inventory": 0.8, "orders": 0.7, "restaurant-management": 0.7, "kitchen-display": 0.6, "online-payments": 0.6, "1c-bas": 0.5, "table-ordering": 0.5, "liqpay": 0.4, "monobank": 0.4 },
  "poster": { "pos-system": 0.9, "inventory": 0.8, "restaurant-management": 0.8, "restaurants": 0.8, "checkbox": 0.7, "online-menu": 0.7, "orders": 0.7, "kitchen-display": 0.6, "google-sheets": 0.5, "reports": 0.5, "table-booking": 0.5, "table-ordering": 0.5 },
  "postgresql": { "backups": 0.55, "api-backend": 0.45, "monitoring": 0.45, "data-import": 0.35, "docker": 0.35, "reports": 0.35 },
  "pregnancy-app": { "calendar": 0.8, "mobile-app": 0.7, "notifications": 0.7, "parenting-app": 0.7, "user-account": 0.4 },
  "presentations": { "branding": 0.5, "copywriting": 0.5, "ui-ux-design": 0.4, "consulting": 0.3, "video-editing": 0.3 },
  "price-monitoring": { "parser": 0.8, "data-analytics": 0.7, "notifications": 0.6, "reports": 0.6, "search": 0.6, "ecommerce": 0.5, "geolocation": 0.5, "hotline": 0.5, "online-store": 0.5, "data-import": 0.4, "demand-forecasting": 0.4, "google-sheets": 0.3 },
  "printing": { "forms": 0.7, "file-upload": 0.6, "orders": 0.6, "online-payments": 0.5, "online-store": 0.5, "quotations": 0.5, "content-editor": 0.4, "delivery": 0.4, "invoicing": 0.4 },
  "prisma": { "postgresql": 0.8, "typescript": 0.7, "nodejs": 0.6, "migration": 0.5, "testing": 0.5, "github-actions": 0.4, "mysql": 0.4 },
  "privatbank": { "online-payments": 0.9, "apple-google-pay": 0.7, "invoicing": 0.6, "refunds": 0.6, "api-backend": 0.5, "checkbox": 0.5, "webhooks": 0.4, "accounting": 0.3, "expense-management": 0.3 },
  "procurement": { "inventory": 0.9, "invoicing": 0.7, "orders": 0.7, "supplier-portal": 0.7, "reports": 0.6, "roles": 0.6, "warehouse-management": 0.5 },
  "product-analytics": { "data-analytics": 0.6, "google-analytics": 0.55, "reports": 0.55, "demand-forecasting": 0.5, "web-app": 0.4, "testing": 0.35 },
  "product-bundles": { "online-store": 0.9, "cart-checkout": 0.8, "catalog": 0.7, "inventory": 0.7, "orders": 0.6, "loyalty": 0.4 },
  "product-photo": { "content-filling": 0.6, "online-store": 0.6, "ecommerce": 0.5, "branding": 0.4, "smm": 0.4, "video-editing": 0.4 },
  "prom": { "online-store": 0.9, "catalog": 0.8, "orders": 0.8, "keycrm": 0.7, "nova-poshta": 0.7, "online-payments": 0.7, "delivery": 0.6, "inventory": 0.6, "reports": 0.5, "wholesale-pricing": 0.4, "product-bundles": 0.3 },
  "prompt-engineering": { "ai-integration": 0.7, "ai-text": 0.5, "anthropic": 0.5, "openai": 0.5, "rag": 0.5, "ai-agent": 0.4, "gemini": 0.4, "testing": 0.4 },
  "property-management": { "maintenance-management": 0.8, "invoicing": 0.7, "notifications": 0.6, "user-account": 0.6, "contract-management": 0.5, "online-payments": 0.5 },
  "prozorro": { "tender-monitoring": 0.8, "government": 0.7, "procurement": 0.7, "notifications": 0.6, "reports": 0.6, "data-import": 0.5, "opendatabot": 0.4 },
  "psychology": { "online-booking": 0.8, "calendar": 0.7, "video-calls": 0.6, "forms": 0.5, "notifications": 0.5, "online-payments": 0.5, "clinic-management": 0.4, "user-account": 0.4 },
  "pwa": { "offline-mode": 0.7, "notifications": 0.6, "ui-ux-design": 0.5, "web-analytics": 0.5, "app-store-publishing": 0.3 },
  "python": { "api-backend": 0.5, "testing": 0.5, "github": 0.45, "postgresql": 0.45, "docker": 0.4, "pandas": 0.35 },
  "qr": { "online-payments": 0.5, "online-menu": 0.4, "checkbox": 0.3, "notifications": 0.3 },
  "quality-management": { "manufacturing-execution": 0.8, "reports": 0.7, "tasks": 0.6, "data-analytics": 0.5, "inventory": 0.5, "file-upload": 0.4 },
  "queue": { "notifications": 0.6, "qr": 0.5, "realtime": 0.5, "calendar": 0.4, "online-booking": 0.4, "sms": 0.4 },
  "quiz": { "forms": 0.8, "reports": 0.6, "game": 0.5, "web-analytics": 0.5, "email-marketing": 0.4, "notifications": 0.4 },
  "quotations": { "invoicing": 0.9, "crm": 0.7, "e-signature": 0.7, "accounting": 0.5, "online-payments": 0.5, "sales-pipeline": 0.5, "user-account": 0.4 },
  "rag": { "data-import": 0.7, "semantic-search": 0.7, "openai": 0.6, "ai-integration": 0.5, "monitoring": 0.5, "summarization": 0.5, "testing": 0.5, "anthropic": 0.4 },
  "react": { "typescript": 0.65, "nextjs": 0.55, "testing": 0.5, "web-app": 0.5, "github": 0.45, "vite": 0.4, "ui-ux-design": 0.35 },
  "react-native": { "mobile-app": 0.75, "expo": 0.65, "app-store-publishing": 0.6, "typescript": 0.55, "firebase": 0.45, "testing": 0.45, "android-app": 0.4, "ios-app": 0.4 },
  "real-estate": { "directory": 0.8, "search": 0.8, "forms": 0.7, "real-estate-listing-platform": 0.7, "maps-stores": 0.6, "property-management": 0.6, "crm-setup": 0.5, "google-maps": 0.5, "photo-video": 0.4, "user-profiles": 0.4 },
  "real-estate-listing-platform": { "real-estate": 0.9, "search": 0.9, "maps-stores": 0.7, "classifieds": 0.6, "user-profiles": 0.6, "forms": 0.5 },
  "real-estate-website": { "real-estate": 0.9, "catalog": 0.8, "forms": 0.7, "maps-stores": 0.6, "search": 0.6, "real-estate-listing-platform": 0.5 },
  "realtime": { "notifications": 0.5, "webhooks": 0.5, "chat": 0.4, "monitoring": 0.4, "user-account": 0.3 },
  "recipes-app": { "meal-planner": 0.8, "search": 0.8, "shopping-list": 0.8, "mobile-app": 0.6, "wishlist": 0.6, "offline-mode": 0.4 },
  "recommendations": { "catalog": 0.6, "user-account": 0.5, "web-analytics": 0.5, "data-analytics": 0.4, "online-store": 0.4 },
  "recruitment-agency": { "ats": 0.8, "job-board": 0.8, "crm": 0.7, "forms": 0.6, "search": 0.6, "ai-recruiter": 0.5, "notifications": 0.5, "email-marketing": 0.4, "user-profiles": 0.4, "linkedin": 0.3 },
  "redesign": { "ui-ux-design": 0.8, "seo": 0.6, "ux-research": 0.6, "performance": 0.5, "testing": 0.5 },
  "redis": { "docker": 0.6, "monitoring": 0.6, "nodejs": 0.6, "architecture": 0.5, "aws": 0.5, "performance": 0.5, "postgresql": 0.4 },
  "refactoring": { "testing": 0.7, "architecture": 0.6, "code-review": 0.6, "performance": 0.5, "monitoring": 0.4 },
  "referral": { "user-account": 0.6, "marketing-automation": 0.5, "notifications": 0.5, "web-analytics": 0.4, "online-payments": 0.3 },
  "refunds": { "online-payments": 0.8, "orders": 0.6, "checkbox": 0.4, "invoicing": 0.4, "notifications": 0.4 },
  "rehab": { "online-booking": 0.7, "patient-records": 0.7, "calendar": 0.6, "clinic-management": 0.5, "notifications": 0.5, "online-payments": 0.5, "fitness-app": 0.4, "forms": 0.4, "helsi": 0.4 },
  "religion": { "donation-platform": 0.6, "religion-app": 0.6, "events": 0.5, "online-payments": 0.5, "multilingual": 0.4, "notifications": 0.4, "website": 0.4 },
  "religion-app": { "religion": 0.9, "mobile-app": 0.7, "notifications": 0.6, "calendar": 0.5, "multilingual": 0.5, "content-editor": 0.4 },
  "reminder-app": { "notifications": 0.9, "calendar": 0.8, "mobile-app": 0.7, "tasks": 0.6, "web-app": 0.5, "realtime": 0.4 },
  "remix": { "react": 0.7, "typescript": 0.7, "postgresql": 0.6, "prisma": 0.6, "github-actions": 0.5, "vercel": 0.5 },
  "rental-management": { "calendar": 0.9, "inventory": 0.8, "rental-marketplace": 0.8, "online-booking": 0.7, "online-payments": 0.6, "notifications": 0.5 },
  "rental-marketplace": { "marketplace": 0.9, "online-booking": 0.9, "online-payments": 0.8, "rental-management": 0.8, "user-profiles": 0.7, "calendar": 0.6, "search": 0.6 },
  "replit": { "github": 0.5, "web-app": 0.5, "api-backend": 0.4, "postgresql": 0.4, "testing": 0.4, "docker": 0.35, "monitoring": 0.35 },
  "reports": { "data-analytics": 0.6, "data-import": 0.5, "excel": 0.5, "google-sheets": 0.5, "monitoring": 0.3 },
  "resend": { "notifications": 0.8, "email-marketing": 0.7, "api-backend": 0.5, "webhooks": 0.5, "auth": 0.4 },
  "restaurant-management": { "pos-system": 0.9, "inventory": 0.8, "orders": 0.8, "kitchen-display": 0.7, "online-menu": 0.7, "poster": 0.6, "restaurant-website": 0.5 },
  "restaurant-website": { "online-menu": 0.9, "restaurants": 0.9, "table-booking": 0.8, "maps-stores": 0.7, "online-booking": 0.6 },
  "restaurants": { "online-menu": 0.8, "restaurant-management": 0.7, "table-booking": 0.7, "delivery": 0.6, "online-payments": 0.6, "orders": 0.6, "poster": 0.6, "kitchen-display": 0.5, "table-ordering": 0.5, "checkbox": 0.4, "glovo": 0.4, "loyalty": 0.4, "nova-poshta": 0.3 },
  "retail": { "inventory": 0.8, "pos-system": 0.8, "checkbox": 0.7, "online-store": 0.6, "orders": 0.6, "1c-bas": 0.5, "loyalty": 0.5, "online-payments": 0.5, "reports": 0.5, "warehouse-management": 0.5, "demand-forecasting": 0.4, "keycrm": 0.4, "prom": 0.4 },
  "retool": { "internal-tool": 0.75, "postgresql": 0.5, "auth": 0.45, "roles": 0.45, "reports": 0.4 },
  "reviews": { "user-account": 0.5, "moderation": 0.4, "notifications": 0.4, "online-store": 0.4, "seo": 0.3, "web-analytics": 0.3 },
  "roles": { "auth": 0.7, "user-account": 0.6, "two-factor": 0.5, "monitoring": 0.4, "sso": 0.4 },
  "route-planning": { "delivery": 0.9, "geolocation": 0.9, "maps-stores": 0.7, "realtime": 0.7, "fleet-management": 0.6, "delivery-app": 0.5, "notifications": 0.5 },
  "rozetka": { "online-store": 0.9, "catalog": 0.8, "orders": 0.8, "keycrm": 0.7, "delivery": 0.6, "inventory": 0.6, "nova-poshta": 0.6, "online-payments": 0.6, "reports": 0.5, "product-bundles": 0.3, "wholesale-pricing": 0.3 },
  "rozetka-delivery": { "delivery": 0.7, "online-store": 0.7, "orders": 0.7, "cart-checkout": 0.6, "shipment-management": 0.6, "inventory": 0.5, "nova-poshta": 0.4, "ukrposhta": 0.4, "webhooks": 0.4 },
  "rpa": { "automation": 0.9, "browser-automation": 0.8, "data-import": 0.6, "workflow-builder": 0.6, "python": 0.5, "monitoring": 0.4 },
  "saas": { "auth": 0.8, "subscriptions": 0.8, "roles": 0.7, "monitoring": 0.6, "online-payments": 0.6, "user-account": 0.6, "backups": 0.5, "support": 0.4 },
  "sales-pipeline": { "crm": 0.9, "tasks": 0.7, "ai-sales-assistant": 0.6, "email-marketing": 0.6, "quotations": 0.6, "reports": 0.6, "notifications": 0.5, "web-analytics": 0.4 },
  "salesdrive": { "orders": 0.8, "crm": 0.7, "inventory": 0.7, "online-store": 0.7, "sales-pipeline": 0.7, "sync": 0.7, "nova-poshta": 0.6, "reports": 0.5, "online-payments": 0.4, "quotations": 0.4 },
  "school-management": { "education": 0.9, "calendar": 0.8, "notifications": 0.7, "online-payments": 0.6, "user-account": 0.6, "roles": 0.5 },
  "science": { "data-analytics": 0.7, "data-import": 0.6, "reports": 0.6, "api-backend": 0.5, "backups": 0.4, "data-warehouse": 0.4, "file-upload": 0.4, "github": 0.4, "monitoring": 0.4 },
  "search": { "catalog": 0.6, "semantic-search": 0.6, "recommendations": 0.4, "web-analytics": 0.4, "multilingual": 0.3 },
  "security-audit": { "bug-fixing": 0.7, "architecture": 0.6, "code-review": 0.6, "backups": 0.5, "devops": 0.5, "monitoring": 0.5, "testing": 0.5, "crypto-wallet": 0.3 },
  "security-services": { "forms": 0.7, "monitoring": 0.6, "security-audit": 0.6, "geolocation": 0.5, "notifications": 0.5, "online-booking": 0.5, "reports": 0.4, "roles": 0.4 },
  "semantic-search": { "search": 0.9, "rag": 0.8, "vector-database": 0.8, "ai-assistant": 0.6, "data-import": 0.4, "openai": 0.4 },
  "sendpulse": { "email-marketing": 0.8, "marketing-automation": 0.8, "chat-bot": 0.7, "sms": 0.7, "notifications": 0.5, "telegram-api": 0.5, "sync": 0.4 },
  "sendpulse-bots": { "chat-bot": 0.7, "telegram-api": 0.55, "ai-customer-support": 0.5, "marketing-automation": 0.5, "crm": 0.45, "telegram-bot": 0.45, "viber-api": 0.4, "viber-bot": 0.35 },
  "sentry": { "monitoring": 0.8, "github": 0.6, "performance": 0.5, "testing": 0.5, "github-actions": 0.4, "support": 0.4 },
  "seo": { "web-analytics": 0.7, "copywriting": 0.6, "content-filling": 0.5, "performance": 0.5, "google-analytics": 0.4, "google-merchant": 0.4, "search": 0.4 },
  "services-marketplace": { "multi-vendor": 0.8, "online-payments": 0.7, "reviews": 0.7, "search": 0.7, "user-profiles": 0.7, "booking-platform": 0.6, "chat": 0.5, "moderation": 0.5, "notifications": 0.5 },
  "shipment-management": { "delivery": 0.9, "nova-poshta": 0.8, "orders": 0.8, "notifications": 0.7, "fleet-management": 0.5, "route-planning": 0.5 },
  "shipping-calculator": { "online-store": 0.9, "cart-checkout": 0.8, "delivery": 0.8, "nova-poshta": 0.8, "ukrposhta": 0.6, "meest": 0.5 },
  "shopify": { "online-store": 0.8, "cart-checkout": 0.75, "catalog": 0.65, "digital-goods-store": 0.6, "online-payments": 0.6, "product-bundles": 0.6, "subscription-store": 0.6, "delivery": 0.55, "gift-cards": 0.5, "orders": 0.5, "wholesale-pricing": 0.5, "nova-poshta": 0.45, "web-analytics": 0.45, "inventory": 0.4, "liqpay": 0.4, "wayforpay": 0.4, "checkbox": 0.35, "monobank": 0.35 },
  "shopping-list": { "meal-planner": 0.8, "sync": 0.8, "mobile-app": 0.7, "recipes-app": 0.7, "notifications": 0.6, "family-organizer": 0.5 },
  "slack": { "ai-meeting-notes": 0.6, "notifications": 0.55, "webhooks": 0.5, "workflow-builder": 0.5, "automation": 0.45, "team-bot": 0.45, "github": 0.4, "task-manager": 0.4, "jira": 0.35 },
  "slack-bot": { "slack": 0.9, "bot-scenarios": 0.7, "automation": 0.5, "notifications": 0.5 },
  "sleep-tracker": { "mobile-app": 0.8, "notifications": 0.6, "reports": 0.6, "fitness-app": 0.5, "calendar": 0.4, "sync": 0.4 },
  "smm": { "copywriting": 0.7, "ads": 0.5, "branding": 0.5, "facebook": 0.5, "instagram": 0.5, "video-editing": 0.5, "analytics-setup": 0.4 },
  "sms": { "notifications": 0.7, "turbosms": 0.7, "orders": 0.4, "viber-api": 0.4, "auth": 0.3 },
  "social-sharing": { "marketing-automation": 0.6, "web-analytics": 0.5, "content-editor": 0.4, "facebook": 0.4, "referral": 0.4, "dating-app": 0.3 },
  "softr": { "airtable": 0.55, "web-app": 0.55, "auth": 0.45, "directory": 0.4, "roles": 0.4, "ui-ux-design": 0.4, "internal-tool": 0.35 },
  "spec-writing": { "architecture": 0.7, "consulting": 0.6, "testing": 0.5, "ui-ux-design": 0.4, "ux-research": 0.4, "security-audit": 0.3, "workflow-builder": 0.3 },
  "speech-to-text": { "ai-text": 0.5, "forms": 0.4, "openai": 0.4, "notifications": 0.3, "translation": 0.3 },
  "sports-clubs": { "class-schedule": 0.8, "memberships": 0.8, "online-booking": 0.7, "online-payments": 0.6, "fitness-app": 0.5, "notifications": 0.5, "qr": 0.4, "user-account": 0.4 },
  "sports-fan-app": { "notifications": 0.8, "realtime": 0.8, "sports-clubs": 0.8, "mobile-app": 0.7, "calendar": 0.6, "web-app": 0.5 },
  "sqlite": { "testing": 0.6, "backups": 0.5, "migration": 0.5, "architecture": 0.4 },
  "sso": { "auth": 0.8, "microsoft-365": 0.5, "roles": 0.5, "two-factor": 0.4, "security-audit": 0.3 },
  "strapi": { "content-editor": 0.8, "postgresql": 0.7, "nextjs": 0.6, "seo": 0.5, "aws": 0.4, "typescript": 0.4, "web-app": 0.4 },
  "streaming-platform": { "video-streaming": 0.9, "subscriptions": 0.8, "recommendations": 0.7, "user-account": 0.7, "search": 0.6, "online-payments": 0.5 },
  "stripe": { "online-payments": 0.9, "cart-checkout": 0.8, "subscriptions": 0.7, "webhooks": 0.7, "apple-google-pay": 0.6, "refunds": 0.6, "api-backend": 0.5, "digital-goods-store": 0.4, "subscription-store": 0.4 },
  "subscription-store": { "online-store": 0.9, "subscriptions": 0.9, "cart-checkout": 0.8, "online-payments": 0.8, "orders": 0.7, "invoicing": 0.5, "loyalty": 0.4 },
  "subscriptions": { "online-payments": 0.8, "notifications": 0.6, "subscription-store": 0.6, "user-account": 0.6, "invoicing": 0.5, "online-store": 0.4, "refunds": 0.4, "loyalty": 0.3 },
  "summarization": { "ai-assistant": 0.8, "openai": 0.6, "rag": 0.6, "speech-to-text": 0.6, "ai-text": 0.5, "document-management": 0.4 },
  "supabase": { "postgresql": 0.7, "auth": 0.6, "backups": 0.45, "web-app": 0.45, "monitoring": 0.4, "webhooks": 0.4 },
  "supplier-portal": { "procurement": 0.9, "catalog": 0.8, "orders": 0.8, "user-account": 0.8, "b2b-portal": 0.6, "inventory": 0.6, "invoicing": 0.6 },
  "support": { "bug-fixing": 0.6, "monitoring": 0.6, "backups": 0.5, "documentation": 0.4, "security-audit": 0.4 },
  "support-chat-services": { "chat": 0.8, "ai-customer-support": 0.7, "helpdesk": 0.65, "notifications": 0.55, "crm": 0.5, "forms": 0.4, "web-app": 0.4 },
  "svelte": { "typescript": 0.55, "web-app": 0.5, "github": 0.45, "testing": 0.45, "vercel": 0.4, "vite": 0.4 },
  "swift": { "ios-app": 0.75, "app-store-publishing": 0.7, "mobile-app": 0.65, "testing": 0.5, "auth": 0.35 },
  "sync": { "data-import": 0.6, "webhooks": 0.6, "1c-bas": 0.4, "api-backend": 0.4, "google-sheets": 0.4, "monitoring": 0.4 },
  "table-booking": { "online-booking": 0.8, "calendar": 0.6, "notifications": 0.5, "online-menu": 0.5, "restaurants": 0.5 },
  "table-ordering": { "qr": 0.9, "restaurants": 0.9, "orders": 0.8, "online-menu": 0.7, "online-payments": 0.7, "restaurant-management": 0.6, "food-ordering": 0.5, "kitchen-display": 0.5 },
  "tailwind": { "react": 0.45, "ui-ux-design": 0.45, "nextjs": 0.4, "figma": 0.35, "typescript": 0.35, "vite": 0.35 },
  "task-manager": { "auth": 0.7, "tasks": 0.7, "notifications": 0.6, "planner-app": 0.6, "roles": 0.6, "calendar": 0.5, "comments": 0.5, "reminder-app": 0.5, "user-profiles": 0.4 },
  "tasks": { "planner-app": 0.6, "notifications": 0.5, "reminder-app": 0.5, "calendar": 0.4, "comments": 0.4, "user-account": 0.4, "reports": 0.3 },
  "taxi-app": { "geolocation": 0.9, "notifications": 0.7, "online-payments": 0.7, "realtime": 0.7, "route-planning": 0.7, "google-maps": 0.6, "orders": 0.5, "uklon-bolt": 0.5 },
  "team-bot": { "notifications": 0.7, "tasks": 0.6, "telegram-api": 0.6, "automation": 0.5, "bot-scenarios": 0.5, "slack": 0.5, "workflow-builder": 0.5 },
  "telegram-api": { "telegram-bot": 0.9, "notifications": 0.7, "automation": 0.6, "chat": 0.6, "webhooks": 0.5, "ai-customer-support": 0.4 },
  "telegram-bot": { "telegram-api": 0.9, "bot-scenarios": 0.8, "chat-bot": 0.8, "notifications": 0.6, "ai-customer-support": 0.5, "aiogram": 0.5, "forms": 0.5, "crm-setup": 0.4 },
  "telegram-mini-app": { "telegram-api": 0.9, "auth": 0.6, "online-payments": 0.6, "bot-scenarios": 0.5, "ui-ux-design": 0.5, "testing": 0.4 },
  "tender-monitoring": { "prozorro": 0.9, "notifications": 0.7, "reports": 0.6, "search": 0.6, "data-analytics": 0.5, "parser": 0.5, "data-import": 0.4, "opendatabot": 0.4, "email-marketing": 0 },
  "testing": { "browser-automation": 0.6, "bug-fixing": 0.6, "github-actions": 0.6, "code-review": 0.4, "monitoring": 0.4, "performance": 0.4, "security-audit": 0.4, "ai-code-scaling": 0.3 },
  "threejs": { "performance": 0.7, "typescript": 0.7, "blender": 0.6, "web-app": 0.6, "gsap": 0.5, "animations": 0.4 },
  "ticketing-platform": { "events": 0.9, "event-registration": 0.8, "online-payments": 0.8, "qr": 0.8, "notifications": 0.6, "email-marketing": 0.5 },
  "tiktok": { "smm": 0.8, "ads": 0.7, "video-editing": 0.7, "content-editor": 0.5, "social-sharing": 0.5, "marketing-automation": 0.4, "youtube": 0.4 },
  "tilda": { "landing": 0.65, "forms": 0.55, "online-payments": 0.45, "web-analytics": 0.45, "seo": 0.4 },
  "time-tracking": { "reports": 0.6, "tasks": 0.5, "invoicing": 0.4, "planner-app": 0.4, "user-account": 0.4, "google-sheets": 0.3 },
  "trae": { "github": 0.6, "testing": 0.6, "ai-code-fix": 0.5, "code-review": 0.5 },
  "transit-app": { "realtime": 0.9, "geolocation": 0.8, "maps-stores": 0.8, "mobile-app": 0.8, "notifications": 0.7, "search": 0.5 },
  "translation": { "multilingual": 0.7, "localization": 0.5, "ai-text": 0.4, "content-editor": 0.4, "openai": 0.3 },
  "transport": { "booking-platform": 0.7, "fleet-management": 0.7, "geolocation": 0.7, "route-planning": 0.7, "online-payments": 0.6, "maps-stores": 0.5, "notifications": 0.5, "orders": 0.4, "uklon-bolt": 0.4 },
  "travel": { "online-booking": 0.8, "online-payments": 0.7, "multilingual": 0.6, "travel-planner": 0.6, "booking-platform": 0.5, "calendar": 0.5, "notifications": 0.5, "forms": 0.4, "google-maps": 0.4, "maps-stores": 0.4, "ticketing-platform": 0.4 },
  "travel-planner": { "travel": 0.9, "calendar": 0.8, "booking-platform": 0.7, "maps-stores": 0.7, "mobile-app": 0.6, "notifications": 0.5 },
  "trello": { "tasks": 0.9, "calendar": 0.5, "comments": 0.5, "notifications": 0.5, "google-calendar": 0.4, "google-drive": 0.4 },
  "turbosms": { "sms": 0.9, "notifications": 0.8, "crm": 0.5, "marketing-automation": 0.5, "orders": 0.5, "sync": 0.4, "webhooks": 0.4 },
  "twilio": { "sms": 0.7, "notifications": 0.65, "call-tracking": 0.5, "auth": 0.45, "voice-bot": 0.4, "webhooks": 0.4 },
  "two-factor": { "auth": 0.8, "notifications": 0.5, "monitoring": 0.4, "sso": 0.4 },
  "typescript": { "javascript": 0.55, "testing": 0.5, "github": 0.45, "github-actions": 0.4, "nodejs": 0.4, "monitoring": 0.35 },
  "ui-ux-design": { "figma": 0.7, "ux-research": 0.6, "accessibility": 0.5, "testing": 0.5, "branding": 0.4, "redesign": 0.4, "ar-app": 0.3 },
  "uklon-bolt": { "taxi-app": 0.75, "geolocation": 0.65, "route-planning": 0.6, "notifications": 0.5, "online-payments": 0.45, "maps-stores": 0.35 },
  "ukrposhta": { "delivery": 0.7, "orders": 0.7, "online-store": 0.6, "shipment-management": 0.6, "cart-checkout": 0.5, "online-payments": 0.5, "meest": 0.4, "nova-poshta": 0.4, "webhooks": 0.4 },
  "unity": { "game": 0.9, "dotnet": 0.8, "blender": 0.6, "testing": 0.6, "app-store-publishing": 0.5, "mobile-app": 0.5, "android-app": 0.4, "ios-app": 0.4 },
  "unreal": { "game": 0.9, "blender": 0.7, "performance": 0.6, "testing": 0.5, "app-store-publishing": 0.4, "unity": 0 },
  "user-account": { "auth": 0.8, "notifications": 0.5, "roles": 0.5, "sso": 0.4, "two-factor": 0.3 },
  "user-profiles": { "user-account": 0.7, "auth": 0.6, "reviews": 0.5, "community": 0.4, "search": 0.4, "moderation": 0.3, "notifications": 0.3 },
  "utilities": { "online-payments": 0.7, "notifications": 0.6, "user-account": 0.6, "reports": 0.5, "diia": 0.4, "forms": 0.4, "google-maps": 0.4 },
  "ux-research": { "ui-ux-design": 0.8, "redesign": 0.6, "testing": 0.6, "accessibility": 0.5, "analytics-setup": 0.4 },
  "v0": { "nextjs": 0.7, "tailwind": 0.65, "vercel": 0.55, "figma": 0.4, "supabase": 0.4 },
  "vchasno": { "e-signature": 0.9, "document-management": 0.7, "invoicing": 0.7, "1c-bas": 0.6, "contract-management": 0.6, "microsoft-365": 0.4, "webhooks": 0.4 },
  "vector-database": { "rag": 0.9, "semantic-search": 0.9, "ai-assistant": 0.7, "langchain": 0.6, "data-import": 0.4, "openai": 0.4 },
  "vercel": { "nextjs": 0.65, "github": 0.55, "monitoring": 0.45, "web-app": 0.45 },
  "veterinary": { "online-booking": 0.8, "patient-records": 0.7, "notifications": 0.6, "pet-care-app": 0.6, "clinic-management": 0.5, "forms": 0.5, "online-payments": 0.5, "inventory": 0.4, "maps-stores": 0.4, "web-app": 0.4 },
  "viber-api": { "viber-bot": 0.9, "notifications": 0.7, "marketing-automation": 0.6, "sendpulse": 0.5, "sms": 0.5, "webhooks": 0.5, "ai-customer-support": 0.3 },
  "viber-bot": { "viber-api": 0.9, "bot-scenarios": 0.8, "notifications": 0.6, "crm-setup": 0.4, "turbosms": 0.4 },
  "video-calls": { "zoom": 0.6, "calendar": 0.5, "notifications": 0.5, "realtime": 0.5, "user-account": 0.5, "video-streaming": 0.3 },
  "video-editing": { "motion-design": 0.5, "smm": 0.5, "youtube": 0.5, "copywriting": 0.4, "product-photo": 0.4 },
  "video-editor-app": { "video-editing": 0.8, "file-upload": 0.7, "mobile-app": 0.7, "animations": 0.6, "offline-mode": 0.5, "subscriptions": 0.4 },
  "video-streaming": { "realtime": 0.5, "monitoring": 0.4, "subscriptions": 0.4, "user-account": 0.4, "web-analytics": 0.3 },
  "vite": { "typescript": 0.7, "react": 0.6, "tailwind": 0.6, "github-actions": 0.5, "vercel": 0.5, "nextjs": 0.4, "performance": 0.4 },
  "voice-bot": { "call-tracking": 0.7, "speech-to-text": 0.7, "ai-integration": 0.6, "twilio": 0.6, "notifications": 0.4 },
  "vps": { "devops": 0.8, "docker": 0.7, "monitoring": 0.7, "backups": 0.6, "github-actions": 0.5, "security-audit": 0.5, "cloudflare": 0.4 },
  "vr-app": { "unity": 0.8, "unreal": 0.8, "game": 0.7, "threejs": 0.6, "mobile-app": 0.4, "ui-ux-design": 0.4 },
  "vue": { "nuxt": 0.55, "typescript": 0.55, "web-app": 0.5, "github": 0.45, "testing": 0.45, "vite": 0.4 },
  "waitlist": { "notifications": 0.9, "online-booking": 0.7, "email-marketing": 0.6, "orders": 0.5, "calendar": 0.4, "online-store": 0.4 },
  "warehouse-management": { "inventory": 0.9, "orders": 0.8, "barcode-scanner": 0.7, "reports": 0.7, "shipment-management": 0.6, "data-import": 0.5 },
  "wayforpay": { "online-payments": 0.9, "cart-checkout": 0.8, "orders": 0.7, "refunds": 0.6, "webhooks": 0.6, "api-backend": 0.5, "apple-google-pay": 0.5, "subscriptions": 0.4, "digital-goods-store": 0.3, "subscription-store": 0.3 },
  "weather-app": { "geolocation": 0.9, "mobile-app": 0.8, "notifications": 0.7, "web-app": 0.5, "maps-stores": 0.4, "realtime": 0.4 },
  "web-analytics": { "google-analytics": 0.7, "reports": 0.6, "product-analytics": 0.5, "marketing-automation": 0.4, "legal-docs": 0 },
  "web-app": { "auth": 0.7, "api-backend": 0.6, "roles": 0.6, "monitoring": 0.5, "testing": 0.5, "backups": 0.4, "security-audit": 0.4 },
  "web-portal": { "auth": 0.7, "roles": 0.7, "content-editor": 0.6, "search": 0.6, "forms": 0.5, "multilingual": 0.5, "accessibility": 0.4 },
  "web3": { "crypto-payments": 0.7, "security-audit": 0.7, "auth": 0.5, "webhooks": 0.4 },
  "webflow": { "seo": 0.55, "ui-ux-design": 0.55, "forms": 0.45, "landing": 0.45, "web-analytics": 0.45, "content-editor": 0.4 },
  "webhooks": { "api-backend": 0.7, "sync": 0.6, "monitoring": 0.5, "documentation": 0.4, "notifications": 0.3 },
  "website": { "ui-ux-design": 0.7, "content-editor": 0.6, "forms": 0.5, "seo": 0.5, "web-analytics": 0.5, "accessibility": 0.4 },
  "wedding-platform": { "weddings": 0.9, "forms": 0.7, "event-registration": 0.6, "online-booking": 0.6, "multilingual": 0.5 },
  "weddings": { "forms": 0.7, "online-booking": 0.7, "wedding-platform": 0.7, "calendar": 0.6, "online-payments": 0.5, "portfolio-site": 0.5, "event-registration": 0.4, "instagram": 0.4 },
  "whatsapp-api": { "whatsapp-bot": 0.9, "chat": 0.8, "crm": 0.6, "notifications": 0.6, "ai-customer-support": 0.5, "marketing-automation": 0.5, "webhooks": 0.5, "ai-sales-assistant": 0.4 },
  "whatsapp-bot": { "whatsapp-api": 0.9, "bot-scenarios": 0.8, "notifications": 0.6, "crm-setup": 0.5, "turbosms": 0.4 },
  "white-label": { "auth": 0.5, "roles": 0.5, "saas": 0.5, "multilingual": 0.4, "subscriptions": 0.4, "branding": 0.3, "monitoring": 0.3 },
  "wholesale": { "catalog": 0.8, "orders": 0.8, "1c-bas": 0.7, "inventory": 0.7, "invoicing": 0.7, "wholesale-pricing": 0.7, "delivery": 0.6, "supplier-portal": 0.5, "warehouse-management": 0.5, "keycrm": 0.4, "online-payments": 0.4 },
  "wholesale-pricing": { "b2b-portal": 0.9, "wholesale": 0.9, "catalog": 0.7, "user-account": 0.7, "invoicing": 0.6, "orders": 0.5, "supplier-portal": 0.5 },
  "wiki": { "content-editor": 0.7, "search": 0.7, "auth": 0.6, "roles": 0.6, "backups": 0.5, "semantic-search": 0.5, "summarization": 0.5 },
  "windsurf": { "github": 0.6, "testing": 0.5, "github-actions": 0.45, "code-review": 0.4, "typescript": 0.4 },
  "wishlist": { "catalog": 0.7, "online-store": 0.5, "user-account": 0.5, "notifications": 0.4, "recommendations": 0.4 },
  "wix": { "website": 0.65, "online-booking": 0.45, "seo": 0.45, "web-analytics": 0.45, "forms": 0.4, "online-payments": 0.4 },
  "woocommerce": { "online-store": 0.8, "cart-checkout": 0.75, "nova-poshta": 0.7, "catalog": 0.65, "online-payments": 0.65, "delivery": 0.6, "digital-goods-store": 0.6, "product-bundles": 0.6, "subscription-store": 0.6, "checkbox": 0.55, "liqpay": 0.55, "orders": 0.55, "ukrposhta": 0.55, "wayforpay": 0.55, "gift-cards": 0.5, "monobank": 0.45, "inventory": 0.4, "prom": 0.4, "rozetka": 0.4, "seo": 0.4, "wholesale-pricing": 0.4 },
  "wordpress": { "website": 0.65, "content-editor": 0.6, "seo": 0.6, "web-analytics": 0.45, "security-audit": 0.4 },
  "workflow-builder": { "automation": 0.9, "n8n": 0.8, "webhooks": 0.8, "make-com": 0.7, "api-backend": 0.6, "realtime": 0.4 },
  "workforce-scheduling": { "calendar": 0.9, "time-tracking": 0.8, "hr-system": 0.7, "notifications": 0.6, "reports": 0.6, "restaurant-management": 0.5, "roles": 0.5 },
  "youtube": { "video-editing": 0.8, "smm": 0.7, "video-streaming": 0.6, "ads": 0.5, "content-editor": 0.5, "streaming-platform": 0.4 },
  "zapier": { "workflow-builder": 0.8, "automation": 0.75, "google-sheets": 0.5, "webhooks": 0.5, "notifications": 0.45, "crm": 0.4, "rpa": 0.4, "api-backend": 0.35 },
  "zed": { "github": 0.6, "testing": 0.6, "code-review": 0.5, "docker": 0.4 },
  "zoom": { "video-calls": 0.9, "calendar": 0.6, "ai-meeting-notes": 0.5, "lms": 0.5, "notifications": 0.5 },
};
