// Components copied from the official lucide-animated registry; aliases keep existing UI imports stable.
export { ArrowLeftIcon as ArrowLeft } from "./animated/arrow-left";
export { ArrowRightIcon as ArrowRight } from "./animated/arrow-right";
export { ArrowUpIcon as ArrowUp } from "./animated/arrow-up";
export { ArrowUpRightIcon as ArrowUpRight } from "./animated/arrow-up-right";
export { BellIcon as Bell } from "./animated/bell";
export { CheckIcon as Check } from "./animated/check";
export { ChevronDownIcon as ChevronDown } from "./animated/chevron-down";
export { ChevronRightIcon as ChevronRight } from "./animated/chevron-right";
export { ChevronUpIcon as ChevronUp } from "./animated/chevron-up";
export { ClockIcon as Clock } from "./animated/clock";
export { FileTextIcon as FileText } from "./animated/file-text";
export { LockIcon as Lock } from "./animated/lock";
export { MapPinIcon as MapPin } from "./animated/map-pin";
export { MessageCircleIcon as MessageCircle } from "./animated/message-circle";
export { PlusIcon as Plus } from "./animated/plus";
export { SendIcon as Send } from "./animated/send";
export { ShieldCheckIcon as ShieldCheck } from "./animated/shield-check";
export { SlidersHorizontalIcon as SlidersHorizontal } from "./animated/sliders-horizontal";
export { UsersIcon as Users } from "./animated/users";
export { WalletIcon as Wallet } from "./animated/wallet";
export { XIcon as X } from "./animated/x";
export { CalendarDaysIcon as CalendarClock } from "./animated/calendar-days";
export { SwitchCameraIcon as Camera } from "./animated/switch-camera";
export { ArrowRightIcon as ChevronsRight } from "./animated/arrow-right";
export { FolderCodeIcon as Code2 } from "./animated/folder-code";
export { GalleryThumbnailsIcon as ImageIcon } from "./animated/gallery-thumbnails";
export { MailboxIcon as Inbox } from "./animated/mailbox";
export { BookTextIcon as Info } from "./animated/book-text";
export { ClipboardCheckIcon as ListChecks } from "./animated/clipboard-check";
export { LoaderCircleIcon as Loader2 } from "./animated/loader-circle";
export { LogoutIcon as LogOut } from "./animated/logout";
export { MailboxIcon as Mail } from "./animated/mailbox";
export { MapPinIcon as MapPinned } from "./animated/map-pin";
export { MessageSquareIcon as MessageSquareText } from "./animated/message-square";
export { MenuIcon as MoreHorizontal } from "./animated/menu";
export { AttachFileIcon as Paperclip } from "./animated/attach-file";
export { DeleteIcon as Trash2 } from "./animated/delete";
export { UserIcon as UserRound } from "./animated/user";
export { Star } from "./star";
export { QrCode } from "./qr-code";
export { Eraser } from "./eraser";
export { Scale } from "./scale";
